//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HUDT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HUDT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.Controls.HUDT", typeof(HUDT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARMED.
        /// </summary>
        public static string ARMED {
            get {
                return ResourceManager.GetString("ARMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AS .
        /// </summary>
        public static string AS {
            get {
                return ResourceManager.GetString("AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bat .
        /// </summary>
        public static string Bat {
            get {
                return ResourceManager.GetString("Bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISARMED.
        /// </summary>
        public static string DISARMED {
            get {
                return ResourceManager.GetString("DISARMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILSAFE.
        /// </summary>
        public static string FAILSAFE {
            get {
                return ResourceManager.GetString("FAILSAFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int FailsafeH {
            get {
                object obj = ResourceManager.GetObject("FailsafeH", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arial.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS: No GPS.
        /// </summary>
        public static string GPS0 {
            get {
                return ResourceManager.GetString("GPS0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS: No Fix.
        /// </summary>
        public static string GPS1 {
            get {
                return ResourceManager.GetString("GPS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS: 2D Fix.
        /// </summary>
        public static string GPS2 {
            get {
                return ResourceManager.GetString("GPS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS: 3D Fix.
        /// </summary>
        public static string GPS3 {
            get {
                return ResourceManager.GetString("GPS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS: 3D dgps.
        /// </summary>
        public static string GPS4 {
            get {
                return ResourceManager.GetString("GPS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS: rtk Float.
        /// </summary>
        public static string GPS5 {
            get {
                return ResourceManager.GetString("GPS5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS: rtk Fixed.
        /// </summary>
        public static string GPS6 {
            get {
                return ResourceManager.GetString("GPS6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GS .
        /// </summary>
        public static string GS {
            get {
                return ResourceManager.GetString("GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        public static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.
        /// </summary>
        public static string NW {
            get {
                return ResourceManager.GetString("NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        public static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
    }
}
