//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionPlanner {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissionPlanner.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Params 的本地化字符串。
        /// </summary>
        public static string AdvancedParams {
            get {
                return ResourceManager.GetString("AdvancedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to upload  的本地化字符串。
        /// </summary>
        public static string AreYouSureYouWantToUpload {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto WP 的本地化字符串。
        /// </summary>
        public static string AutoWP {
            get {
                return ResourceManager.GetString("AutoWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad Battery 的本地化字符串。
        /// </summary>
        public static string Bad_Battery {
            get {
                return ResourceManager.GetString("Bad_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad KML File : 的本地化字符串。
        /// </summary>
        public static string Bad_KML_File {
            get {
                return ResourceManager.GetString("Bad_KML_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad Proximity 的本地化字符串。
        /// </summary>
        public static string Bad_Proximity {
            get {
                return ResourceManager.GetString("Bad_Proximity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad SatCom 的本地化字符串。
        /// </summary>
        public static string Bad_SatCom {
            get {
                return ResourceManager.GetString("Bad_SatCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad Vision Position 的本地化字符串。
        /// </summary>
        public static string Bad_Vision_Position {
            get {
                return ResourceManager.GetString("Bad_Vision_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad Accel Health 的本地化字符串。
        /// </summary>
        public static string BadAccelHealth {
            get {
                return ResourceManager.GetString("BadAccelHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhealthy AHRS 的本地化字符串。
        /// </summary>
        public static string BadAHRS {
            get {
                return ResourceManager.GetString("BadAHRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhealthy Airspeed 的本地化字符串。
        /// </summary>
        public static string BadAirspeed {
            get {
                return ResourceManager.GetString("BadAirspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad Baro Health 的本地化字符串。
        /// </summary>
        public static string BadBaroHealth {
            get {
                return ResourceManager.GetString("BadBaroHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad Compass Health 的本地化字符串。
        /// </summary>
        public static string BadCompassHealth {
            get {
                return ResourceManager.GetString("BadCompassHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad Lat/Lng 的本地化字符串。
        /// </summary>
        public static string BadCoords {
            get {
                return ResourceManager.GetString("BadCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhealthy GPS Signal 的本地化字符串。
        /// </summary>
        public static string BadGPSHealth {
            get {
                return ResourceManager.GetString("BadGPSHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad Gyro Health 的本地化字符串。
        /// </summary>
        public static string BadGyroHealth {
            get {
                return ResourceManager.GetString("BadGyroHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad LiDAR Health 的本地化字符串。
        /// </summary>
        public static string BadLiDARHealth {
            get {
                return ResourceManager.GetString("BadLiDARHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad Logging 的本地化字符串。
        /// </summary>
        public static string BadLogging {
            get {
                return ResourceManager.GetString("BadLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad OptFlow Health 的本地化字符串。
        /// </summary>
        public static string BadOptFlowHealth {
            get {
                return ResourceManager.GetString("BadOptFlowHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad or No Terrain Data 的本地化字符串。
        /// </summary>
        public static string BadorNoTerrainData {
            get {
                return ResourceManager.GetString("BadorNoTerrainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Tuning 的本地化字符串。
        /// </summary>
        public static string BasicTuning {
            get {
                return ResourceManager.GetString("BasicTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beta 的本地化字符串。
        /// </summary>
        public static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 These are beta firmware, use at your own risk!!! 的本地化字符串。
        /// </summary>
        public static string BetaWarning {
            get {
                return ResourceManager.GetString("BetaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not connect to com port and detect board type 的本地化字符串。
        /// </summary>
        public static string CanNotConnectToComPortAnd {
            get {
                return ResourceManager.GetString("CanNotConnectToComPortAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot graph this field 的本地化字符串。
        /// </summary>
        public static string CannotGraphField {
            get {
                return ResourceManager.GetString("CannotGraphField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cant detect your Board version. Please check your cabling 的本地化字符串。
        /// </summary>
        public static string CantDetectBoardVersion {
            get {
                return ResourceManager.GetString("CantDetectBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Throttle 的本地化字符串。
        /// </summary>
        public static string ChangeThrottle {
            get {
                return ResourceManager.GetString("ChangeThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking  的本地化字符串。
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check port settings or Port in use? 的本地化字符串。
        /// </summary>
        public static string CheckPortSettingsOr {
            get {
                return ResourceManager.GetString("CheckPortSettingsOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click when Done 的本地化字符串。
        /// </summary>
        public static string Click_when_Done {
            get {
                return ResourceManager.GetString("Click_when_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Command failed to execute
        /// 的本地化字符串。
        /// </summary>
        public static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Communication Error - no connection 的本地化字符串。
        /// </summary>
        public static string CommunicationErrorNoConnection {
            get {
                return ResourceManager.GetString("CommunicationErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 compass variance 的本地化字符串。
        /// </summary>
        public static string compass_variance {
            get {
                return ResourceManager.GetString("compass_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed 的本地化字符串。
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect 的本地化字符串。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CONNECT 的本地化字符串。
        /// </summary>
        public static string CONNECTc {
            get {
                return ResourceManager.GetString("CONNECTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect Failed 的本地化字符串。
        /// </summary>
        public static string ConnectFailed {
            get {
                return ResourceManager.GetString("ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connecting Mavlink 的本地化字符串。
        /// </summary>
        public static string ConnectingMavlink {
            get {
                return ResourceManager.GetString("ConnectingMavlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue 的本地化字符串。
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converting bin to log 的本地化字符串。
        /// </summary>
        public static string Converting_bin_to_log {
            get {
                return ResourceManager.GetString("Converting_bin_to_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description:  的本地化字符串。
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected a  的本地化字符串。
        /// </summary>
        public static string DetectedA {
            get {
                return ResourceManager.GetString("DetectedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detecting Board Version 的本地化字符串。
        /// </summary>
        public static string DetectingBoardVersion {
            get {
                return ResourceManager.GetString("DetectingBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DISCONNECT 的本地化字符串。
        /// </summary>
        public static string DISCONNECTc {
            get {
                return ResourceManager.GetString("DISCONNECTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to load this into the flight data screen? 的本地化字符串。
        /// </summary>
        public static string Do_you_want_to_load_this_into_the_flight_data_screen {
            get {
                return ResourceManager.GetString("Do_you_want_to_load_this_into_the_flight_data_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloaded from internet 的本地化字符串。
        /// </summary>
        public static string DownloadedFromInternet {
            get {
                return ResourceManager.GetString("DownloadedFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading from Internet 的本地化字符串。
        /// </summary>
        public static string DownloadingFromInternet {
            get {
                return ResourceManager.GetString("DownloadingFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ensure your props are not on the Plane/Quad 的本地化字符串。
        /// </summary>
        public static string EnsurePropsNotOn {
            get {
                return ResourceManager.GetString("EnsurePropsNotOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Epprom changed, all your setting will be lost during the update,
        ///Do you wish to continue? 的本地化字符串。
        /// </summary>
        public static string EppromChanged {
            get {
                return ResourceManager.GetString("EppromChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Epprom format changed ({0) vs {1}) 的本地化字符串。
        /// </summary>
        public static string EppromFormatChanged {
            get {
                return ResourceManager.GetString("EppromFormatChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error binding 的本地化字符串。
        /// </summary>
        public static string Error_binding {
            get {
                return ResourceManager.GetString("Error_binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error closing log files 的本地化字符串。
        /// </summary>
        public static string ErrorClosingLogFile {
            get {
                return ResourceManager.GetString("ErrorClosingLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error communicating with the autopilot 的本地化字符串。
        /// </summary>
        public static string ErrorCommunicating {
            get {
                return ResourceManager.GetString("ErrorCommunicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Connecting
        /// 的本地化字符串。
        /// </summary>
        public static string ErrorConnecting {
            get {
                return ResourceManager.GetString("ErrorConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature is not enabled in your firmware. 的本地化字符串。
        /// </summary>
        public static string ErrorFeatureNotEnabled {
            get {
                return ResourceManager.GetString("ErrorFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error loading firmware file 的本地化字符串。
        /// </summary>
        public static string ErrorFirmwareFile {
            get {
                return ResourceManager.GetString("ErrorFirmwareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error receiving log list 的本地化字符串。
        /// </summary>
        public static string ErrorLogList {
            get {
                return ResourceManager.GetString("ErrorLogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: no response from MAV 的本地化字符串。
        /// </summary>
        public static string ErrorNoResponse {
            get {
                return ResourceManager.GetString("ErrorNoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not connected. 的本地化字符串。
        /// </summary>
        public static string ErrorNotConnected {
            get {
                return ResourceManager.GetString("ErrorNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error receiving list
        /// 的本地化字符串。
        /// </summary>
        public static string ErrorReceivingParams {
            get {
                return ResourceManager.GetString("ErrorReceivingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: command rejected by MAV 的本地化字符串。
        /// </summary>
        public static string ErrorRejectedByMAV {
            get {
                return ResourceManager.GetString("ErrorRejectedByMAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error renaming file 的本地化字符串。
        /// </summary>
        public static string ErrorRenameFile {
            get {
                return ResourceManager.GetString("ErrorRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error setting parameter  的本地化字符串。
        /// </summary>
        public static string ErrorSettingParameter {
            get {
                return ResourceManager.GetString("ErrorSettingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set {0} Failed 的本地化字符串。
        /// </summary>
        public static string ErrorSetValueFailed {
            get {
                return ResourceManager.GetString("ErrorSetValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error uploading firmware 的本地化字符串。
        /// </summary>
        public static string ErrorUploadingFirmware {
            get {
                return ResourceManager.GetString("ErrorUploadingFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extended Tuning 的本地化字符串。
        /// </summary>
        public static string ExtendedTuning {
            get {
                return ResourceManager.GetString("ExtendedTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create ground station log - wont log this session 的本地化字符串。
        /// </summary>
        public static string Failclog {
            get {
                return ResourceManager.GetString("Failclog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to connect to SITL instance 的本地化字符串。
        /// </summary>
        public static string Failed_to_connect_to_SITL_instance {
            get {
                return ResourceManager.GetString("Failed_to_connect_to_SITL_instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to download the SITL image. 的本地化字符串。
        /// </summary>
        public static string Failed_to_download_the_SITL_image {
            get {
                return ResourceManager.GetString("Failed_to_download_the_SITL_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed download 的本地化字符串。
        /// </summary>
        public static string FailedDownload {
            get {
                return ResourceManager.GetString("FailedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed read HEX 的本地化字符串。
        /// </summary>
        public static string FailedReadHEX {
            get {
                return ResourceManager.GetString("FailedReadHEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read firmware.hex : 的本地化字符串。
        /// </summary>
        public static string FailedToReadHex {
            get {
                return ResourceManager.GetString("FailedToReadHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed upload 的本地化字符串。
        /// </summary>
        public static string FailedUpload {
            get {
                return ResourceManager.GetString("FailedUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FailSafe 的本地化字符串。
        /// </summary>
        public static string FailSafe {
            get {
                return ResourceManager.GetString("FailSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flight Modes 的本地化字符串。
        /// </summary>
        public static string FlightModes {
            get {
                return ResourceManager.GetString("FlightModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Parameter List 的本地化字符串。
        /// </summary>
        public static string FullParameterList {
            get {
                return ResourceManager.GetString("FullParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Parameter Tree 的本地化字符串。
        /// </summary>
        public static string FullParameterTree {
            get {
                return ResourceManager.GetString("FullParameterTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GeoFence 的本地化字符串。
        /// </summary>
        public static string GeoFence {
            get {
                return ResourceManager.GetString("GeoFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Geofence Breach 的本地化字符串。
        /// </summary>
        public static string GeofenceBreach {
            get {
                return ResourceManager.GetString("GeofenceBreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting  的本地化字符串。
        /// </summary>
        public static string Getting {
            get {
                return ResourceManager.GetString("Getting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting FW List 的本地化字符串。
        /// </summary>
        public static string GettingFWList {
            get {
                return ResourceManager.GetString("GettingFWList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting FW Version 的本地化字符串。
        /// </summary>
        public static string GettingFWVersion {
            get {
                return ResourceManager.GetString("GettingFWVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting Params 的本地化字符串。
        /// </summary>
        public static string GettingParams {
            get {
                return ResourceManager.GetString("GettingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting Params... 的本地化字符串。
        /// </summary>
        public static string GettingParamsD {
            get {
                return ResourceManager.GetString("GettingParamsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting updated parameters 的本地化字符串。
        /// </summary>
        public static string GettingUpdatedParams {
            get {
                return ResourceManager.GetString("GettingUpdatedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Got param  的本地化字符串。
        /// </summary>
        public static string Gotparam {
            get {
                return ResourceManager.GetString("Gotparam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid home location 的本地化字符串。
        /// </summary>
        public static string Invalid_home_location {
            get {
                return ResourceManager.GetString("Invalid_home_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Location 的本地化字符串。
        /// </summary>
        public static string Invalid_Location {
            get {
                return ResourceManager.GetString("Invalid_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Alt 的本地化字符串。
        /// </summary>
        public static string InvalidAlt {
            get {
                return ResourceManager.GetString("InvalidAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid BaudRate 的本地化字符串。
        /// </summary>
        public static string InvalidBaudRate {
            get {
                return ResourceManager.GetString("InvalidBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Board Type 的本地化字符串。
        /// </summary>
        public static string InvalidBoardType {
            get {
                return ResourceManager.GetString("InvalidBoardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Cert 的本地化字符串。
        /// </summary>
        public static string InvalidCert {
            get {
                return ResourceManager.GetString("InvalidCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Field 的本地化字符串。
        /// </summary>
        public static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid FileName 的本地化字符串。
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid number entered
        /// 的本地化字符串。
        /// </summary>
        public static string InvalidNumberEntered {
            get {
                return ResourceManager.GetString("InvalidNumberEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Pan Range 的本地化字符串。
        /// </summary>
        public static string InvalidPanRange {
            get {
                return ResourceManager.GetString("InvalidPanRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid PortName 的本地化字符串。
        /// </summary>
        public static string InvalidPortName {
            get {
                return ResourceManager.GetString("InvalidPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Tilt Range 的本地化字符串。
        /// </summary>
        public static string InvalidTiltRange {
            get {
                return ResourceManager.GetString("InvalidTiltRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Update Rate 的本地化字符串。
        /// </summary>
        public static string InvalidUpdateRate {
            get {
                return ResourceManager.GetString("InvalidUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link Stats 的本地化字符串。
        /// </summary>
        public static string LinkStats {
            get {
                return ResourceManager.GetString("LinkStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load data 的本地化字符串。
        /// </summary>
        public static string Load_data {
            get {
                return ResourceManager.GetString("Load_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please click ok and move the autopilot around all axises in a circular motion 的本地化字符串。
        /// </summary>
        public static string MagCalibMsg {
            get {
                return ResourceManager.GetString("MagCalibMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAVFtp 的本地化字符串。
        /// </summary>
        public static string MAVFtp {
            get {
                return ResourceManager.GetString("MAVFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mavlink Connecting... 的本地化字符串。
        /// </summary>
        public static string MavlinkConnecting {
            get {
                return ResourceManager.GetString("MavlinkConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are missing data points. do you want to run the calibration anyway? 的本地化字符串。
        /// </summary>
        public static string MissingDataPoints {
            get {
                return ResourceManager.GetString("MissingDataPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Firmware 的本地化字符串。
        /// </summary>
        public static string NewFirmware {
            get {
                return ResourceManager.GetString("NewFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New firmware available
        /// 的本地化字符串。
        /// </summary>
        public static string NewFirmwareA {
            get {
                return ResourceManager.GetString("NewFirmwareA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No firmware available for this board! 的本地化字符串。
        /// </summary>
        public static string No_firmware_available_for_this_board {
            get {
                return ResourceManager.GetString("No_firmware_available_for_this_board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No valid heartbeats read from port 的本地化字符串。
        /// </summary>
        public static string No_valid_heartbeats_read_from_port {
            get {
                return ResourceManager.GetString("No_valid_heartbeats_read_from_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No valid sik radio 的本地化字符串。
        /// </summary>
        public static string No_valid_sik_radio {
            get {
                return ResourceManager.GetString("No_valid_sik_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No FMT message for  的本地化字符串。
        /// </summary>
        public static string NoFMTMessage {
            get {
                return ResourceManager.GetString("NoFMTMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No need to upload. already on the board 的本地化字符串。
        /// </summary>
        public static string NoNeedToUpload {
            get {
                return ResourceManager.GetString("NoNeedToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NO RC Receiver 的本地化字符串。
        /// </summary>
        public static string NORCReceiver {
            get {
                return ResourceManager.GetString("NORCReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not available when used as a windows store app 的本地化字符串。
        /// </summary>
        public static string Not_available_when_used_as_a_windows_store_app {
            get {
                return ResourceManager.GetString("Not_available_when_used_as_a_windows_store_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note 的本地化字符串。
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Obtain From Module 的本地化字符串。
        /// </summary>
        public static string ObtainFromModule {
            get {
                return ResourceManager.GetString("ObtainFromModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Onboard OSD 的本地化字符串。
        /// </summary>
        public static string OnboardOSD {
            get {
                return ResourceManager.GetString("OnboardOSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only 1 Heatbeat Received 的本地化字符串。
        /// </summary>
        public static string Only1Hb {
            get {
                return ResourceManager.GetString("Only1Hb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only 1 Mavlink Heartbeat Packets was read from this port - Verify your hardware is setup correctly
        ///Mission Planner waits for 2 valid heartbeat packets before connecting 的本地化字符串。
        /// </summary>
        public static string Only1HbD {
            get {
                return ResourceManager.GetString("Only1HbD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Param refresh is required - Please press F5
        ///old #{0}  new #{1} 的本地化字符串。
        /// </summary>
        public static string ParamRefreshRequired {
            get {
                return ResourceManager.GetString("ParamRefreshRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Planner 的本地化字符串。
        /// </summary>
        public static string Planner {
            get {
                return ResourceManager.GetString("Planner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please connect first 的本地化字符串。
        /// </summary>
        public static string PleaseConnect {
            get {
                return ResourceManager.GetString("PleaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please connect and backup your config in the configuration tab. 的本地化字符串。
        /// </summary>
        public static string PleaseConnectAndBackupConfig {
            get {
                return ResourceManager.GetString("PleaseConnectAndBackupConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please load a valid file 的本地化字符串。
        /// </summary>
        public static string PleaseLoadValidFile {
            get {
                return ResourceManager.GetString("PleaseLoadValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a cell first 的本地化字符串。
        /// </summary>
        public static string PleaseSelectCell {
            get {
                return ResourceManager.GetString("PleaseSelectCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please unplug the board, and then press OK and plug back in.
        ///Mission Planner will look for 30 seconds to find the board 的本地化字符串。
        /// </summary>
        public static string PleaseUnplugTheBoardAnd {
            get {
                return ResourceManager.GetString("PleaseUnplugTheBoardAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///Please upgrade 的本地化字符串。
        /// </summary>
        public static string Pleaseup {
            get {
                return ResourceManager.GetString("Pleaseup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please wait for the musical tones to finish before clicking OK 的本地化字符串。
        /// </summary>
        public static string PleaseWaitForTheMusicalTones {
            get {
                return ResourceManager.GetString("PleaseWaitForTheMusicalTones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pos horiz variance 的本地化字符串。
        /// </summary>
        public static string pos_horiz_variance {
            get {
                return ResourceManager.GetString("pos_horiz_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pos vert variance 的本地化字符串。
        /// </summary>
        public static string pos_vert_variance {
            get {
                return ResourceManager.GetString("pos_vert_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prearm check failed - check messages 的本地化字符串。
        /// </summary>
        public static string Prearm_check_failed {
            get {
                return ResourceManager.GetString("Prearm_check_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sucessfully programmed 的本地化字符串。
        /// </summary>
        public static string ProgrammedOK {
            get {
                return ResourceManager.GetString("ProgrammedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Put the transmitter in bind mode. Receiver is waiting. 的本地化字符串。
        /// </summary>
        public static string Put_the_transmitter_in_bind_mode__Receiver_is_waiting {
            get {
                return ResourceManager.GetString("Put_the_transmitter_in_bind_mode__Receiver_is_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ? 的本地化字符串。
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raw Param Warning 的本地化字符串。
        /// </summary>
        public static string RawParamWarning {
            get {
                return ResourceManager.GetString("RawParamWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All values on this screen are not min/max checked. Please double check your input.
        ///Please use Standard/Advanced Params for the safe settings 的本地化字符串。
        /// </summary>
        public static string RawParamWarningi {
            get {
                return ResourceManager.GetString("RawParamWarningi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading Hex 的本地化字符串。
        /// </summary>
        public static string ReadingHex {
            get {
                return ResourceManager.GetString("ReadingHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading Hex File 的本地化字符串。
        /// </summary>
        public static string ReadingHexFile {
            get {
                return ResourceManager.GetString("ReadingHexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received List 的本地化字符串。
        /// </summary>
        public static string ReceivedList {
            get {
                return ResourceManager.GetString("ReceivedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 run anyway 的本地化字符串。
        /// </summary>
        public static string RunAnyway {
            get {
                return ResourceManager.GetString("RunAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving 的本地化字符串。
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanning File 的本地化字符串。
        /// </summary>
        public static string Scanning_File {
            get {
                return ResourceManager.GetString("Scanning_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a comport 的本地化字符串。
        /// </summary>
        public static string SelectComport {
            get {
                return ResourceManager.GetString("SelectComport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Here 的本地化字符串。
        /// </summary>
        public static string SetHere {
            get {
                return ResourceManager.GetString("SetHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show me again? 的本地化字符串。
        /// </summary>
        public static string ShowMeAgain {
            get {
                return ResourceManager.GetString("ShowMeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard Params 的本地化字符串。
        /// </summary>
        public static string StandardParams {
            get {
                return ResourceManager.GetString("StandardParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your model is still moving are you sure you want to disconnect? 的本地化字符串。
        /// </summary>
        public static string Stillmoving {
            get {
                return ResourceManager.GetString("Stillmoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 terrain alt variance 的本地化字符串。
        /// </summary>
        public static string terrain_alt_variance {
            get {
                return ResourceManager.GetString("terrain_alt_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This board has been retired, Mission Planner this will upload the last available version to your board (AC 3.2.1/AP 3.4.0) 的本地化字符串。
        /// </summary>
        public static string ThisBoardHasBeenRetired {
            get {
                return ResourceManager.GetString("ThisBoardHasBeenRetired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout waiting for autoscan/no mavlink device connected 的本地化字符串。
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tracker Home 的本地化字符串。
        /// </summary>
        public static string TrackerHome {
            get {
                return ResourceManager.GetString("TrackerHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 trunk 的本地化字符串。
        /// </summary>
        public static string Trunk {
            get {
                return ResourceManager.GetString("Trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 These are the latest trunk firmware, use at your own risk!!! 的本地化字符串。
        /// </summary>
        public static string TrunkWarning {
            get {
                return ResourceManager.GetString("TrunkWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trying to connect.
        ///Timeout in {0} 的本地化字符串。
        /// </summary>
        public static string Trying {
            get {
                return ResourceManager.GetString("Trying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Units: {0}{1} 的本地化字符串。
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Found
        ///
        ///Do you wish to update now?  的本地化字符串。
        /// </summary>
        public static string UpdateFound {
            get {
                return ResourceManager.GetString("UpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No update available. 的本地化字符串。
        /// </summary>
        public static string UpdateNotFound {
            get {
                return ResourceManager.GetString("UpdateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Now 的本地化字符串。
        /// </summary>
        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Complete 的本地化字符串。
        /// </summary>
        public static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading {0} bytes to Board: 的本地化字符串。
        /// </summary>
        public static string UploadingBytesToBoard {
            get {
                return ResourceManager.GetString("UploadingBytesToBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload succeeded, but verify failed: exp {0} got {1} at  的本地化字符串。
        /// </summary>
        public static string UploadSucceededButVerifyFailed {
            get {
                return ResourceManager.GetString("UploadSucceededButVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Params 的本地化字符串。
        /// </summary>
        public static string User_Params {
            get {
                return ResourceManager.GetString("User_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 velocity variance 的本地化字符串。
        /// </summary>
        public static string velocity_variance {
            get {
                return ResourceManager.GetString("velocity_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Complete 的本地化字符串。
        /// </summary>
        public static string VerifyComplete {
            get {
                return ResourceManager.GetString("VerifyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Firmware 的本地化字符串。
        /// </summary>
        public static string VerifyFirmware {
            get {
                return ResourceManager.GetString("VerifyFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning, as of AC 3.1 motors will spin when armed, configurable through the MOT_SPIN_ARMED parameter 的本地化字符串。
        /// </summary>
        public static string WarningAC31 {
            get {
                return ResourceManager.GetString("WarningAC31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning, if you are installing AC 3.2 for the first time you MUST redo a Compass calibration. 的本地化字符串。
        /// </summary>
        public static string WarningAC32 {
            get {
                return ResourceManager.GetString("WarningAC32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Browse will not function correctly without FMT messages in your log.
        ///These appear to be missing from your log. 的本地化字符串。
        /// </summary>
        public static string WarningLogBrowseFMTMissing {
            get {
                return ResourceManager.GetString("WarningLogBrowseFMTMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning rally points are located greater than RALLY_LIMIT_KM 的本地化字符串。
        /// </summary>
        public static string Warningrallypointdistance {
            get {
                return ResourceManager.GetString("Warningrallypointdistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Params
        ///DON&apos;T DO THIS IF YOU ARE IN THE AIR
        /// 的本地化字符串。
        /// </summary>
        public static string WarningUpdateParamList {
            get {
                return ResourceManager.GetString("WarningUpdateParamList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using unsupported hardware.
        ///This board does not contain a valid certificate of authenticity.
        ///Please contact your hardware vendor about signing your hardware. 的本地化字符串。
        /// </summary>
        public static string YouAreUsingUnsupportedHardware {
            get {
                return ResourceManager.GetString("YouAreUsingUnsupportedHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WP# {0} has zero altitude, this means no altitude change! If you want zero altitude, change it to 0.01. Do you want to continue or cancel wp upload? 的本地化字符串。
        /// </summary>
        public static string ZeroAltWarningCopter {
            get {
                return ResourceManager.GetString("ZeroAltWarningCopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WP# {0} has zero altitude. If you actually want zero altitude, change it to 0.01 instead for predictable behavior.
        ///
        ///On ArduPlane, zero altitudes may interpreted in two different ways: actual zero altitude, or keep current altitude. WAYPOINT commands will generally honor a zero altitude and LOITER commands will generally interpret it as &quot;use current altitude&quot;, but only if the altitude frame is &quot;relative&quot;. There may be more exceptions and this could change in future versions.
        ///
        ///ONLY SET TO ZERO IF YOU REAL [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ZeroAltWarningPlane {
            get {
                return ResourceManager.GetString("ZeroAltWarningPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zero Altitude Warning 的本地化字符串。
        /// </summary>
        public static string ZeroAltWarningTitle {
            get {
                return ResourceManager.GetString("ZeroAltWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom To 的本地化字符串。
        /// </summary>
        public static string Zoom_To {
            get {
                return ResourceManager.GetString("Zoom_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom to the center or the loaded file? 的本地化字符串。
        /// </summary>
        public static string Zoom_to_the_center_or_the_loaded_file {
            get {
                return ResourceManager.GetString("Zoom_to_the_center_or_the_loaded_file", resourceCulture);
            }
        }
    }
}
