//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionPlanner {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissionPlanner.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bad Lat/Lng 的本地化字符串。
        /// </summary>
        public static string BadCoords {
            get {
                return ResourceManager.GetString("BadCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot graph this field 的本地化字符串。
        /// </summary>
        public static string CannotGraphField {
            get {
                return ResourceManager.GetString("CannotGraphField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cant detect your Board version. Please check your cabling 的本地化字符串。
        /// </summary>
        public static string CantDetectBoardVersion {
            get {
                return ResourceManager.GetString("CantDetectBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking  的本地化字符串。
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check port settings or Port in use? 的本地化字符串。
        /// </summary>
        public static string CheckPortSettingsOr {
            get {
                return ResourceManager.GetString("CheckPortSettingsOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Command failed to execute
        /// 的本地化字符串。
        /// </summary>
        public static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Communication Error - no connection 的本地化字符串。
        /// </summary>
        public static string CommunicationErrorNoConnection {
            get {
                return ResourceManager.GetString("CommunicationErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected a 的本地化字符串。
        /// </summary>
        public static string DetectedA {
            get {
                return ResourceManager.GetString("DetectedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detecting Board Version 的本地化字符串。
        /// </summary>
        public static string DetectingBoardVersion {
            get {
                return ResourceManager.GetString("DetectingBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloaded from internet 的本地化字符串。
        /// </summary>
        public static string DownloadedFromInternet {
            get {
                return ResourceManager.GetString("DownloadedFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading from Internet 的本地化字符串。
        /// </summary>
        public static string DownloadingFromInternet {
            get {
                return ResourceManager.GetString("DownloadingFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Epprom changed, all your setting will be lost during the update,
        ///Do you wish to continue? 的本地化字符串。
        /// </summary>
        public static string EppromChanged {
            get {
                return ResourceManager.GetString("EppromChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Epprom format changed ({0) vs {1}) 的本地化字符串。
        /// </summary>
        public static string EppromFormatChanged {
            get {
                return ResourceManager.GetString("EppromFormatChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error closing log files 的本地化字符串。
        /// </summary>
        public static string ErrorClosingLogFile {
            get {
                return ResourceManager.GetString("ErrorClosingLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error communicating with the autopilot 的本地化字符串。
        /// </summary>
        public static string ErrorCommunicating {
            get {
                return ResourceManager.GetString("ErrorCommunicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Connecting
        /// 的本地化字符串。
        /// </summary>
        public static string ErrorConnecting {
            get {
                return ResourceManager.GetString("ErrorConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature is not enabled in your firmware. 的本地化字符串。
        /// </summary>
        public static string ErrorFeatureNotEnabled {
            get {
                return ResourceManager.GetString("ErrorFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error loading firmware file 的本地化字符串。
        /// </summary>
        public static string ErrorFirmwareFile {
            get {
                return ResourceManager.GetString("ErrorFirmwareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error receiving log list 的本地化字符串。
        /// </summary>
        public static string ErrorLogList {
            get {
                return ResourceManager.GetString("ErrorLogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: no responce from MAV 的本地化字符串。
        /// </summary>
        public static string ErrorNoResponce {
            get {
                return ResourceManager.GetString("ErrorNoResponce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not connected. 的本地化字符串。
        /// </summary>
        public static string ErrorNotConnected {
            get {
                return ResourceManager.GetString("ErrorNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error receiving list
        /// 的本地化字符串。
        /// </summary>
        public static string ErrorReceivingParams {
            get {
                return ResourceManager.GetString("ErrorReceivingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: command rejected by MAV 的本地化字符串。
        /// </summary>
        public static string ErrorRejectedByMAV {
            get {
                return ResourceManager.GetString("ErrorRejectedByMAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error renaming file 的本地化字符串。
        /// </summary>
        public static string ErrorRenameFile {
            get {
                return ResourceManager.GetString("ErrorRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error setting parameter  的本地化字符串。
        /// </summary>
        public static string ErrorSettingParameter {
            get {
                return ResourceManager.GetString("ErrorSettingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set {0} Failed 的本地化字符串。
        /// </summary>
        public static string ErrorSetValueFailed {
            get {
                return ResourceManager.GetString("ErrorSetValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed download 的本地化字符串。
        /// </summary>
        public static string FailedDownload {
            get {
                return ResourceManager.GetString("FailedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed read HEX 的本地化字符串。
        /// </summary>
        public static string FailedReadHEX {
            get {
                return ResourceManager.GetString("FailedReadHEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read firmware.hex : 的本地化字符串。
        /// </summary>
        public static string FailedToReadHex {
            get {
                return ResourceManager.GetString("FailedToReadHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed upload 的本地化字符串。
        /// </summary>
        public static string FailedUpload {
            get {
                return ResourceManager.GetString("FailedUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting  的本地化字符串。
        /// </summary>
        public static string Getting {
            get {
                return ResourceManager.GetString("Getting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting FW List 的本地化字符串。
        /// </summary>
        public static string GettingFWList {
            get {
                return ResourceManager.GetString("GettingFWList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting FW Version 的本地化字符串。
        /// </summary>
        public static string GettingFWVersion {
            get {
                return ResourceManager.GetString("GettingFWVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting updated parameters 的本地化字符串。
        /// </summary>
        public static string GettingUpdatedParams {
            get {
                return ResourceManager.GetString("GettingUpdatedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Alt 的本地化字符串。
        /// </summary>
        public static string InvalidAlt {
            get {
                return ResourceManager.GetString("InvalidAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid BaudRate 的本地化字符串。
        /// </summary>
        public static string InvalidBaudRate {
            get {
                return ResourceManager.GetString("InvalidBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Board Type 的本地化字符串。
        /// </summary>
        public static string InvalidBoardType {
            get {
                return ResourceManager.GetString("InvalidBoardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Field 的本地化字符串。
        /// </summary>
        public static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid FileName 的本地化字符串。
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid number entered
        /// 的本地化字符串。
        /// </summary>
        public static string InvalidNumberEntered {
            get {
                return ResourceManager.GetString("InvalidNumberEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Pan Range 的本地化字符串。
        /// </summary>
        public static string InvalidPanRange {
            get {
                return ResourceManager.GetString("InvalidPanRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid PortName 的本地化字符串。
        /// </summary>
        public static string InvalidPortName {
            get {
                return ResourceManager.GetString("InvalidPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Tilt Range 的本地化字符串。
        /// </summary>
        public static string InvalidTiltRange {
            get {
                return ResourceManager.GetString("InvalidTiltRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Update Rate 的本地化字符串。
        /// </summary>
        public static string InvalidUpdateRate {
            get {
                return ResourceManager.GetString("InvalidUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No FMT message for  的本地化字符串。
        /// </summary>
        public static string NoFMTMessage {
            get {
                return ResourceManager.GetString("NoFMTMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please connect first 的本地化字符串。
        /// </summary>
        public static string PleaseConnect {
            get {
                return ResourceManager.GetString("PleaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please connect and backup your config in the configuration tab. 的本地化字符串。
        /// </summary>
        public static string PleaseConnectAndBackupConfig {
            get {
                return ResourceManager.GetString("PleaseConnectAndBackupConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please load a valid file 的本地化字符串。
        /// </summary>
        public static string PleaseLoadValidFile {
            get {
                return ResourceManager.GetString("PleaseLoadValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a cell first 的本地化字符串。
        /// </summary>
        public static string PleaseSelectCell {
            get {
                return ResourceManager.GetString("PleaseSelectCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading Hex 的本地化字符串。
        /// </summary>
        public static string ReadingHex {
            get {
                return ResourceManager.GetString("ReadingHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading Hex File 的本地化字符串。
        /// </summary>
        public static string ReadingHexFile {
            get {
                return ResourceManager.GetString("ReadingHexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received List 的本地化字符串。
        /// </summary>
        public static string ReceivedList {
            get {
                return ResourceManager.GetString("ReceivedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a comport 的本地化字符串。
        /// </summary>
        public static string SelectComport {
            get {
                return ResourceManager.GetString("SelectComport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Complete 的本地化字符串。
        /// </summary>
        public static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading {0} bytes to Board: 的本地化字符串。
        /// </summary>
        public static string UploadingBytesToBoard {
            get {
                return ResourceManager.GetString("UploadingBytesToBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload succeeded, but verify failed: exp {0} got {1} at  的本地化字符串。
        /// </summary>
        public static string UploadSucceededButVerifyFailed {
            get {
                return ResourceManager.GetString("UploadSucceededButVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Complete 的本地化字符串。
        /// </summary>
        public static string VerifyComplete {
            get {
                return ResourceManager.GetString("VerifyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Firmware 的本地化字符串。
        /// </summary>
        public static string VerifyFirmware {
            get {
                return ResourceManager.GetString("VerifyFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Browse will not function correctly without FMT messages in your log.
        ///These appear to be missing from your log. 的本地化字符串。
        /// </summary>
        public static string WarningLogBrowseFMTMissing {
            get {
                return ResourceManager.GetString("WarningLogBrowseFMTMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Params
        ///DON&apos;T DO THIS IF YOU ARE IN THE AIR
        /// 的本地化字符串。
        /// </summary>
        public static string WarningUpdateParamList {
            get {
                return ResourceManager.GetString("WarningUpdateParamList", resourceCulture);
            }
        }
    }
}
