//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionPlanner.ArduPilot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissionPlanner.ArduPilot.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Vision Position.
        /// </summary>
        internal static string Bad_Vision_Position {
            get {
                return ResourceManager.GetString("Bad_Vision_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Accel Health.
        /// </summary>
        internal static string BadAccelHealth {
            get {
                return ResourceManager.GetString("BadAccelHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad AHRS.
        /// </summary>
        internal static string BadAHRS {
            get {
                return ResourceManager.GetString("BadAHRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Baro Health.
        /// </summary>
        internal static string BadBaroHealth {
            get {
                return ResourceManager.GetString("BadBaroHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Compass Health.
        /// </summary>
        internal static string BadCompassHealth {
            get {
                return ResourceManager.GetString("BadCompassHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad GPS Signal Health.
        /// </summary>
        internal static string BadGPSHealth {
            get {
                return ResourceManager.GetString("BadGPSHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Gyro Health.
        /// </summary>
        internal static string BadGyroHealth {
            get {
                return ResourceManager.GetString("BadGyroHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad LiDAR Health.
        /// </summary>
        internal static string BadLiDARHealth {
            get {
                return ResourceManager.GetString("BadLiDARHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Logging.
        /// </summary>
        internal static string BadLogging {
            get {
                return ResourceManager.GetString("BadLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad OptFlow Health.
        /// </summary>
        internal static string BadOptFlowHealth {
            get {
                return ResourceManager.GetString("BadOptFlowHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad or No Terrain Data.
        /// </summary>
        internal static string BadorNoTerrainData {
            get {
                return ResourceManager.GetString("BadorNoTerrainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compass variance.
        /// </summary>
        internal static string compass_variance {
            get {
                return ResourceManager.GetString("compass_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Failed.
        /// </summary>
        internal static string ConnectFailed {
            get {
                return ResourceManager.GetString("ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting Mavlink.
        /// </summary>
        internal static string ConnectingMavlink {
            get {
                return ResourceManager.GetString("ConnectingMavlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geofence Breach.
        /// </summary>
        internal static string GeofenceBreach {
            get {
                return ResourceManager.GetString("GeofenceBreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting .
        /// </summary>
        internal static string Getting {
            get {
                return ResourceManager.GetString("Getting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Params.
        /// </summary>
        internal static string GettingParams {
            get {
                return ResourceManager.GetString("GettingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Params....
        /// </summary>
        internal static string GettingParamsD {
            get {
                return ResourceManager.GetString("GettingParamsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got param .
        /// </summary>
        internal static string Gotparam {
            get {
                return ResourceManager.GetString("Gotparam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mavlink Connecting....
        /// </summary>
        internal static string MavlinkConnecting {
            get {
                return ResourceManager.GetString("MavlinkConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid heartbeats read from port.
        /// </summary>
        internal static string No_valid_heartbeats_read_from_port {
            get {
                return ResourceManager.GetString("No_valid_heartbeats_read_from_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO RC Receiver.
        /// </summary>
        internal static string NORCReceiver {
            get {
                return ResourceManager.GetString("NORCReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 Heatbeat Received.
        /// </summary>
        internal static string Only1Hb {
            get {
                return ResourceManager.GetString("Only1Hb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 Mavlink Heartbeat Packets was read from this port - Verify your hardware is setup correctly
        ///Mission Planner waits for 2 valid heartbeat packets before connecting.
        /// </summary>
        internal static string Only1HbD {
            get {
                return ResourceManager.GetString("Only1HbD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Param refresh is required - Please press F5
        ///old #{0}  new #{1}.
        /// </summary>
        internal static string ParamRefreshRequired {
            get {
                return ResourceManager.GetString("ParamRefreshRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect first.
        /// </summary>
        internal static string PleaseConnect {
            get {
                return ResourceManager.GetString("PleaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pos horiz variance.
        /// </summary>
        internal static string pos_horiz_variance {
            get {
                return ResourceManager.GetString("pos_horiz_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pos vert variance.
        /// </summary>
        internal static string pos_vert_variance {
            get {
                return ResourceManager.GetString("pos_vert_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terrain alt variance.
        /// </summary>
        internal static string terrain_alt_variance {
            get {
                return ResourceManager.GetString("terrain_alt_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to connect.
        ///Timeout in {0}.
        /// </summary>
        internal static string Trying {
            get {
                return ResourceManager.GetString("Trying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to velocity variance.
        /// </summary>
        internal static string velocity_variance {
            get {
                return ResourceManager.GetString("velocity_variance", resourceCulture);
            }
        }
    }
}
