<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIWaypointPlanner.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>

  <ItemGroup Condition="'$(MissionPlannerHostDir)'!=''">
    <Reference Include="MissionPlanner.Utilities">
      <HintPath>$(MissionPlannerHostDir)\MissionPlanner.Utilities.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MAVLink">
      <HintPath>$(MissionPlannerHostDir)\MAVLink.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
