using System;
using System.Collections.Generic;
using System.Globalization;

namespace MissionPlanner.AIWaypointPlanner
{
    public enum AppLanguage
    {
        English,
        ChineseSimplified,
        Russian
    }

    public sealed class UiLanguageOption
    {
        public UiLanguageOption(AppLanguage language, string languageCode, string displayName)
        {
            Language = language;
            LanguageCode = languageCode;
            DisplayName = displayName;
        }

        public AppLanguage Language { get; private set; }
        public string LanguageCode { get; private set; }
        public string DisplayName { get; private set; }

        public override string ToString()
        {
            return DisplayName;
        }
    }

    public static class UiStrings
    {
        public const string DefaultLanguageCode = "en-US";
        public const string ChineseLanguageCode = "zh-CN";
        public const string RussianLanguageCode = "ru-RU";

        private static readonly IDictionary<string, string> English = CreateEnglish();
        private static readonly IDictionary<string, string> Chinese = CreateChinese();
        private static readonly IDictionary<string, string> Russian = CreateRussian();

        public static string Get(string languageCode, string key)
        {
            if (string.IsNullOrWhiteSpace(key))
                return string.Empty;

            string value;
            IDictionary<string, string> selected = GetCatalog(languageCode);
            if (selected.TryGetValue(key, out value))
                return value;
            if (English.TryGetValue(key, out value))
                return value;
            return key;
        }

        public static string Format(string languageCode, string key, params object[] arguments)
        {
            return string.Format(
                GetCulture(languageCode),
                Get(languageCode, key),
                arguments ?? new object[0]);
        }

        public static string NormalizeLanguageCode(string languageCode)
        {
            if (string.IsNullOrWhiteSpace(languageCode))
                return DefaultLanguageCode;

            string value = languageCode.Trim();
            if (value.Equals(ChineseLanguageCode, StringComparison.OrdinalIgnoreCase) ||
                value.Equals("zh", StringComparison.OrdinalIgnoreCase))
            {
                return ChineseLanguageCode;
            }
            if (value.Equals(RussianLanguageCode, StringComparison.OrdinalIgnoreCase) ||
                value.Equals("ru", StringComparison.OrdinalIgnoreCase))
            {
                return RussianLanguageCode;
            }
            if (value.Equals(DefaultLanguageCode, StringComparison.OrdinalIgnoreCase) ||
                value.Equals("en", StringComparison.OrdinalIgnoreCase))
            {
                return DefaultLanguageCode;
            }
            return DefaultLanguageCode;
        }

        public static AppLanguage ParseLanguage(string languageCode)
        {
            string normalized = NormalizeLanguageCode(languageCode);
            if (normalized == ChineseLanguageCode)
                return AppLanguage.ChineseSimplified;
            if (normalized == RussianLanguageCode)
                return AppLanguage.Russian;
            return AppLanguage.English;
        }

        public static IList<UiLanguageOption> CreateLanguageOptions()
        {
            return new List<UiLanguageOption>
            {
                new UiLanguageOption(AppLanguage.English, DefaultLanguageCode, "English"),
                new UiLanguageOption(AppLanguage.ChineseSimplified, ChineseLanguageCode, "简体中文"),
                new UiLanguageOption(AppLanguage.Russian, RussianLanguageCode, "Русский")
            };
        }

        public static IEnumerable<string> GetEnglishKeys()
        {
            return new List<string>(English.Keys);
        }

        public static IEnumerable<string> GetCatalogKeys(string languageCode)
        {
            return new List<string>(GetCatalog(languageCode).Keys);
        }

        private static IDictionary<string, string> GetCatalog(string languageCode)
        {
            string normalized = NormalizeLanguageCode(languageCode);
            if (normalized == ChineseLanguageCode)
                return Chinese;
            if (normalized == RussianLanguageCode)
                return Russian;
            return English;
        }

        private static CultureInfo GetCulture(string languageCode)
        {
            return CultureInfo.GetCultureInfo(NormalizeLanguageCode(languageCode));
        }

        private static IDictionary<string, string> CreateEnglish()
        {
            return new Dictionary<string, string>(StringComparer.Ordinal)
            {
                { "App.Name", "AI Waypoint Planner" },
                { "App.Title", "AI Waypoint Planner v2.0.0" },
                { "App.MenuTooltip", "Create locally validated candidate waypoints from a natural-language task" },
                { "Safety.Banner", "Safety boundary: GPT creates a constrained candidate mission only. The plugin does not upload a mission, change flight mode, arm, take off, or send RC/PWM commands." },
                { "Nav.Chat", "Chat" },
                { "Nav.Settings", "Settings" },
                { "Nav.MissionReview", "Mission review" },
                { "Nav.Diagnostics", "Diagnostics" },

                { "Chat.WelcomeTitle", "What should the aircraft do?" },
                { "Chat.WelcomeBody", "Describe the mission goal or attach reference files. The proposed mission remains local until you review and apply it." },
                { "Chat.InputPlaceholder", "Describe the mission goal..." },
                { "Chat.NoMessages", "Start with a mission goal or a reference file." },
                { "Chat.NewConversation", "New conversation" },
                { "Chat.ClearConversationPrompt", "Clear the current conversation and candidate mission?" },
                { "Chat.FileCountFormat", "{0} file(s) attached" },
                { "Chat.UserLabel", "You" },
                { "Chat.AssistantLabel", "GPT" },
                { "Chat.SystemLabel", "System" },
                { "Chat.TaskPrompt", "Task" },
                { "Chat.ThinkingLabel", "Thinking" },
                { "Chat.ReasoningSummaryLabel", "Reasoning summary" },
                { "Chat.ClarificationTitle", "More information is required" },
                { "Chat.CandidateReadyTitle", "Candidate mission ready for review" },
                { "Chat.CandidateInvalidTitle", "The candidate mission did not pass local validation" },
                { "Chat.MessageFailed", "The request could not be completed." },
                { "Chat.EmptyObjective", "Enter a mission goal or attach a file before sending." },
                { "Chat.ReviewAction", "Review candidate mission" },
                { "Chat.ViewDiagnostics", "View request diagnostics" },

                { "Status.Idle", "Ready" },
                { "Status.ReadingFiles", "Reading attached files..." },
                { "Status.PreparingRequest", "Preparing the request..." },
                { "Status.Connecting", "Connecting to the model..." },
                { "Status.ReconnectingFormat", "Reconnecting ({0}/{1})..." },
                { "Status.Thinking", "Thinking..." },
                { "Status.WaitingForModel", "Waiting for the model..." },
                { "Status.Validating", "Running local safety validation..." },
                { "Status.Compiling", "Building candidate mission items..." },
                { "Status.ReadyForReview", "Ready for review" },
                { "Status.NeedsClarification", "Waiting for clarification" },
                { "Status.Succeeded", "Completed" },
                { "Status.Failed", "Request failed" },
                { "Status.Cancelled", "Request cancelled" },
                { "Status.TestingConnection", "Testing the connection..." },
                { "Status.ConnectionSucceeded", "Connection successful" },
                { "Status.ConnectionFailed", "Connection failed" },
                { "Status.Applying", "Applying to the local flight plan..." },
                { "Status.AppliedLocally", "Added to the local flight plan; not uploaded" },

                { "Button.Send", "Send" },
                { "Button.Stop", "Stop" },
                { "Button.Attach", "Attach files" },
                { "Button.Remove", "Remove" },
                { "Button.Clear", "Clear" },
                { "Button.Settings", "Settings" },
                { "Button.BackToChat", "Back to chat" },
                { "Button.Close", "Close" },
                { "Button.Save", "Save" },
                { "Button.Cancel", "Cancel" },
                { "Button.Confirm", "Confirm" },
                { "Button.TestConnection", "Test connection" },
                { "Button.SaveProfile", "Save profile" },
                { "Button.DeleteProfile", "Delete profile" },
                { "Button.DeleteSavedKey", "Delete saved key" },
                { "Button.NewChat", "New chat" },
                { "Button.ReviewMission", "Review mission" },
                { "Button.ApplyToPlan", "Apply to flight plan" },
                { "Button.Copy", "Copy" },
                { "Button.CopyCurrentPage", "Copy current page" },
                { "Button.Retry", "Try again" },

                { "Settings.Title", "Settings" },
                { "Settings.Appearance", "Appearance and language" },
                { "Settings.Language", "Interface language" },
                { "Settings.LanguageHelp", "The selection is saved when the plugin closes. English is used when no preference has been saved." },
                { "Settings.Api", "API connection" },
                { "Settings.Provider", "Provider preset" },
                { "Settings.SavedProfile", "Saved profile" },
                { "Settings.BaseUrl", "API base URL" },
                { "Settings.Protocol", "API protocol" },
                { "Settings.Authentication", "Authentication" },
                { "Settings.ModelId", "Model ID" },
                { "Settings.ProjectId", "OpenAI project ID" },
                { "Settings.ApiKey", "API key" },
                { "Settings.RememberKey", "Save in Windows Credential Manager" },
                { "Settings.Reasoning", "Reasoning effort" },
                { "Settings.ReasoningHelp", "Availability depends on the selected model and provider." },
                { "Settings.ConnectionActions", "Connection actions" },
                { "Settings.CredentialStatus", "Credential status" },
                { "Settings.Diagnostics", "Diagnostics" },
                { "Settings.FileHandling", "File handling" },
                { "Settings.ProfileName", "Profile name" },
                { "Settings.ProviderNote", "Provider information" },
                { "Settings.Saved", "Settings saved" },
                { "Settings.RestoredDefaults", "Default settings restored" },

                { "Protocol.Responses", "Responses API (/responses)" },
                { "Protocol.ChatCompletions", "Chat Completions (/chat/completions)" },
                { "Authentication.Bearer", "Bearer API key" },
                { "Authentication.ApiKeyHeader", "api-key header" },
                { "Authentication.None", "No authentication (local gateway)" },

                { "Reasoning.ProviderDefault", "Provider default" },
                { "Reasoning.Low", "Low" },
                { "Reasoning.Medium", "Medium" },
                { "Reasoning.High", "High" },
                { "Reasoning.VeryHigh", "Very high" },
                { "Reasoning.Ultra", "Ultra" },
                { "Reasoning.ProviderDefaultHelp", "Do not send a reasoning-effort parameter." },
                { "Reasoning.Unsupported", "The selected provider or model does not support this reasoning level. Choose Provider default or another supported level." },

                { "Attachment.Title", "Attachments" },
                { "Attachment.Empty", "No files attached" },
                { "Attachment.FileName", "File name" },
                { "Attachment.Type", "Type" },
                { "Attachment.Size", "Size" },
                { "Attachment.Status", "Status" },
                { "Attachment.Ready", "Ready" },
                { "Attachment.Reading", "Reading file" },
                { "Attachment.ImageWillSend", "Image will be sent to the model" },
                { "Attachment.PdfNative", "PDF will be sent as a native file" },
                { "Attachment.PdfText", "PDF text extracted" },
                { "Attachment.DocxText", "DOCX text and tables extracted" },
                { "Attachment.TextRead", "Text read" },
                { "Attachment.Removed", "Attachment removed" },
                { "Attachment.LimitFormat", "Up to {0} files; {1} total" },
                { "Attachment.SomeFailed", "Some files could not be added." },
                { "Attachment.SelectDialogTitle", "Select mission reference files" },
                { "Attachment.DuplicateName", "Two attachments cannot use the same display name." },
                { "Attachment.NoUsedFiles", "The model did not confirm use of any attached file. Generate again or verify file support." },
                { "Attachment.UnrequestedFiles", "The model reported a file that was not attached. Generate again." },
                { "Attachment.UnknownUsedFileFormat", "The model reported an unknown file: {0}" },

                { "Mission.ReviewTitle", "Review candidate mission" },
                { "Mission.Understanding", "Model understanding" },
                { "Mission.Requirements", "Requirements to confirm" },
                { "Mission.UsedFiles", "Files used" },
                { "Mission.NoFiles", "None" },
                { "Mission.CandidateSummary", "Candidate mission" },
                { "Mission.TemplateAndCountFormat", "Template: {0}; candidate items: {1}" },
                { "Mission.Validation", "Local validation" },
                { "Mission.Items", "Candidate mission items" },
                { "Mission.Sequence", "No." },
                { "Mission.Command", "Command" },
                { "Mission.Latitude", "Latitude" },
                { "Mission.Longitude", "Longitude" },
                { "Mission.Altitude", "Altitude (m)" },
                { "Mission.Parameter1", "Parameter 1" },
                { "Mission.Parameter2", "Parameter 2" },
                { "Mission.Description", "Description" },
                { "Mission.ConfirmCheck", "I reviewed and confirm the model's understanding and mission requirements" },
                { "Mission.LocalOnlyNotice", "Applying adds rows to the local Flight Planner only. It does not upload the mission to the flight controller." },
                { "Mission.ExistingItemsWarningFormat", "The flight plan already contains {0} item(s). The candidate items will be appended, not replaced." },
                { "Mission.ApplyConfirmFormat", "Add {0} candidate item(s) to the local Flight Planner?" },
                { "Mission.Applied", "Candidate items were added to the local Flight Planner. Review them before manually writing the mission." },
                { "Mission.RevalidationFailed", "The mission state changed and local revalidation failed. Nothing was applied." },
                { "Mission.NoCandidate", "No valid candidate mission is available." },
                { "Mission.RelativeAltitudeRequired", "Flight Planner altitude mode must be Relative before a candidate can be applied." },
                { "Mission.StandardMissionRequired", "Flight Planner mission type must be Mission before a candidate can be applied." },
                { "Mission.AppendFailedFormat", "The candidate could not be appended; rows added by this operation were rolled back. {0}" },
                { "Mission.CommandChanged", "Mission Planner changed the command while the candidate was being appended. Disable automatic spline conversion and try again." },

                { "Validation.Passed", "Local validation passed." },
                { "Validation.ErrorPrefix", "Error: {0}" },
                { "Validation.WarningPrefix", "Warning: {0}" },
                { "Validation.InfoPrefix", "Info: {0}" },

                { "Diagnostics.Title", "Model response and request diagnostics" },
                { "Diagnostics.RequestMetadata", "Request metadata" },
                { "Diagnostics.RawResponse", "Raw model response" },
                { "Diagnostics.StructuredData", "Structured mission data" },
                { "Diagnostics.DiagnosticInfo", "Diagnostic information" },
                { "Diagnostics.NoRawResponse", "The service did not return a response body." },
                { "Diagnostics.NoStructuredData", "No structured mission data was extracted." },
                { "Diagnostics.NoError", "No error was recorded for this request." },
                { "Diagnostics.RequestedAtFormat", "Requested at: {0}" },
                { "Diagnostics.RequestFormat", "Request: {0} {1}" },
                { "Diagnostics.ProtocolModelFormat", "Protocol / model: {0} / {1}" },
                { "Diagnostics.HttpStatusFormat", "HTTP status: {0}" },
                { "Diagnostics.NoHttpResponse", "No HTTP response" },
                { "Diagnostics.RequestIdFormat", "Request ID: {0}" },
                { "Diagnostics.AttemptsFormat", "Connection attempts: {0}" },
                { "Diagnostics.ReconnectsFormat", "Automatic reconnects: {0}" },

                { "Api.CredentialNone", "No plugin key is required; the local gateway manages credentials." },
                { "Api.CredentialMissing", "No usable API key was found." },
                { "Api.CredentialFoundFormat", "Credential available from {0}; the key is hidden." },
                { "Api.CredentialReadFailedFormat", "Credential check failed: {0}" },
                { "Api.SourceSession", "Current session" },
                { "Api.SourceEnvironment", "OPENAI_API_KEY environment variable" },
                { "Api.SourceWindows", "Windows Credential Manager" },
                { "Api.SourceNone", "None" },
                { "Api.ProfileMissing", "Select a saved connection profile first." },
                { "Api.KeySaved", "The key was saved in Windows Credential Manager." },
                { "Api.KeyDeleted", "The saved key was deleted." },
                { "Api.NoSavedKey", "No saved key was found." },
                { "Api.ProfileLoadedFormat", "Profile loaded: {0}" },
                { "Api.ProfileSavedFormat", "Profile saved: {0}" },
                { "Api.ProfileDeleted", "Profile deleted" },
                { "Api.ProfileNamePrompt", "Enter a name for this connection profile." },
                { "Api.TestSuccessFormat", "Connection successful; credential source: {0}" },
                { "Api.RemoteHttpsRequired", "Remote endpoints must use HTTPS. Plain HTTP is allowed only for a local loopback address." },

                { "TaskSuggestions.Title", "Try a mission task" },
                { "TaskSuggestions.RelativeRoute", "Fly a relative route from planned Home, then return to launch." },
                { "TaskSuggestions.SurveyPolygon", "Survey the polygon drawn in Flight Planner, then return to launch." },
                { "TaskSuggestions.FromFile", "Read the attached mission brief and identify any missing information." },

                { "Dialog.Information", "Information" },
                { "Dialog.Warning", "Warning" },
                { "Dialog.Error", "Error" },
                { "Dialog.ConfirmApply", "Confirm local mission changes" },
                { "Dialog.ConfirmDeleteProfile", "Delete the selected connection profile?" },
                { "Dialog.ConfirmClear", "Clear conversation" },

                { "ProviderName.CcSwitch", "CC Switch (local)" },
                { "ProviderName.OpenAi", "OpenAI" },
                { "ProviderName.OpenRouter", "OpenRouter" },
                { "ProviderName.LiteLlm", "LiteLLM Proxy (local)" },
                { "ProviderName.LmStudio", "LM Studio (local)" },
                { "ProviderName.Ollama", "Ollama (local)" },
                { "ProviderName.NewApi", "New API / One API" },
                { "ProviderName.Azure", "Azure OpenAI" },
                { "ProviderName.Custom", "Custom OpenAI-compatible API" },
                { "ProviderNote.CcSwitch", "Start the CC Switch proxy and route first; CC Switch manages the upstream key or OAuth session." },
                { "ProviderNote.OpenAi", "Use an OpenAI API key; a ChatGPT or Codex login is not itself an API key." },
                { "ProviderNote.OpenRouter", "Use an OpenRouter key and a model ID supported by your account." },
                { "ProviderNote.LiteLlm", "For a local LiteLLM proxy; select no authentication when the proxy has no key." },
                { "ProviderNote.LmStudio", "Load a model in LM Studio and start its local server." },
                { "ProviderNote.Ollama", "Start Ollama and enter the ID of a model already installed locally." },
                { "ProviderNote.NewApi", "Replace the example host with your gateway; compatibility depends on its OpenAI implementation." },
                { "ProviderNote.Azure", "Use the resource v1 base URL and api-key header; the model ID is normally the deployment name." },
                { "ProviderNote.Custom", "Edit the base URL, protocol, authentication and model. Native Anthropic and Gemini protocols are not handled directly." },

                { "Attachment.FilterMissionReferences", "Mission references" },
                { "Attachment.FilterDocuments", "PDF and Office files" },
                { "Attachment.FilterImages", "Image files" },
                { "Attachment.FilterTextData", "Text and data files" },
                { "Attachment.FilterAllFiles", "All files" },
                { "Attachment.DocumentNative", "Document will be sent as a native Responses API file" },
                { "Attachment.ErrorPathRequired", "A file path is required." },
                { "Attachment.ErrorNotFound", "The selected file was not found." },
                { "Attachment.ErrorEmptyFileFormat", "An empty file cannot be attached: {0}" },
                { "Attachment.ErrorFileTooLargeFormat", "A file cannot exceed 12 MB: {0}" },
                { "Attachment.ErrorTooManyFilesFormat", "No more than {0} files can be attached." },
                { "Attachment.ErrorTotalSize", "The combined attachment size cannot exceed 24 MB." },
                { "Attachment.ErrorUnsupportedTypeFormat", "This file type is not supported: {0}. Use PDF, Word/RTF/ODT, PowerPoint, Excel, PNG/JPEG/WebP/GIF, or a common text/data format." },
                { "Attachment.ErrorExtractedTextTotal", "Extracted attachment text cannot exceed 120,000 characters. Reduce or split the source material." },
                { "Attachment.ErrorCountLimit", "The attachment count exceeds the safety limit." },
                { "Attachment.ErrorTotalLimit", "The combined attachment size exceeds the safety limit." },
                { "Attachment.ErrorTextLimit", "The extracted attachment text exceeds the safety limit." },
                { "Attachment.ErrorChatNativeUnsupported", "Chat Completions cannot send this native file and no locally extracted text is available. Use the Responses API or convert the file to readable text; scanned PDFs require OCR." },
                { "Attachment.ErrorImageTooLargeFormat", "An image cannot exceed 8 MB: {0}" },
                { "Attachment.ErrorPdfReadFormat", "The PDF could not be read and may be encrypted or damaged: {0}. {1}" },
                { "Attachment.ErrorDocxXmlMissing", "The DOCX file does not contain word/document.xml." },
                { "Attachment.ErrorDocxReadFormat", "The DOCX file could not be read and may be encrypted or damaged: {0}. {1}" },
                { "Attachment.ErrorDocxEmptyFormat", "The DOCX file has no readable body text: {0}" },
                { "Attachment.ErrorBinaryTextFormat", "The file appears to contain binary data and cannot be read as text: {0}" },
                { "Attachment.ErrorTextEmptyFormat", "The text file has no readable content: {0}" },

                { "Api.ProfileNameTooLong", "The profile name cannot exceed 80 characters." },
                { "Api.ProfileEndpointModelRequired", "Enter an API base URL and model ID first." },
                { "Api.ErrorModelRequired", "A model ID is required." },
                { "Api.ErrorKeyRequired", "The selected authentication method requires an API key." },
                { "Api.ErrorReasoningInvalid", "The reasoning-effort setting is invalid." },
                { "Api.ErrorBaseUrlInvalid", "The API base URL must be a complete HTTP or HTTPS address." },
                { "Api.ErrorBaseUrlQuery", "The API base URL cannot contain a query string or fragment." },
                { "Api.ErrorRemoteHttp", "Plain HTTP is allowed only for a local loopback address; remote APIs must use HTTPS." },
                { "Api.ErrorObjectiveRequired", "A mission objective is required." },
                { "Api.ErrorResponseParseFormat", "The model response could not be parsed: {0}" },
                { "Api.ErrorStructuredParseFormat", "The structured mission JSON could not be deserialized: {0}" },
                { "Api.ErrorStructuredEmpty", "The API returned an empty structured result." },
                { "Api.ErrorEmptyResponse", "The API returned an empty response." },
                { "Api.ErrorResponseInvalid", "The API response could not be parsed." },
                { "Api.ErrorApiReturnedFormat", "The API returned an error: {0}" },
                { "Api.ErrorResponsesOutputMissing", "The Responses API response is missing its output field." },
                { "Api.ErrorRefusalFormat", "The model refused to process the objective: {0}" },
                { "Api.ErrorResponsesIncompleteFormat", "The Responses API response is incomplete: {0}" },
                { "Api.ErrorResponsesTextMissing", "The Responses API response contains no usable structured text." },
                { "Api.ErrorChatResponseInvalid", "The Chat Completions response could not be parsed." },
                { "Api.ErrorChatChoicesMissing", "The Chat Completions response is missing its choices field." },
                { "Api.ErrorChatTextMissing", "The Chat Completions response contains no usable structured text." },
                { "Api.ErrorNoServiceDetails", "The service did not return error details." },
                { "Api.ErrorUnknown", "Unknown error" },
                { "Api.ConnectionRecoveredFormat", "The connection recovered after {0} attempt(s)." },
                { "Api.RequestIdSuffixFormat", " (request ID: {0})" },
                { "Api.HttpFailureFormat", "AI API request failed with HTTP {0}: {1}{2}" },
                { "Api.ErrorTimeoutRetriesExhausted", "The request exceeded the 90-second timeout and automatic reconnection attempts are exhausted." },
                { "Api.ReconnectingFormat", "Temporary connection problem. Reconnecting with attempt {0}/{1} after {2} ms." },
                { "Api.TransportNoDetails", "The API request failed without usable exception details." },
                { "Api.ServiceName", "API service" },
                { "Api.TransportLocalRefusedFormat", "The local API gateway {0} refused the connection. Start the gateway or CC Switch route and verify the base URL and port. Underlying error: {1}" },
                { "Api.TransportLocalFormat", "The local API gateway {0} could not be reached. Check its state, base URL and port. Underlying error: {1}" },
                { "Api.TransportRemoteFormat", "The API service {0} could not be reached. Check the network, base URL, TLS and proxy settings. Underlying error: {1}" },

                { "Mission.CompilationFailedFormat", "Local mission compilation failed: {0}" },
                { "Mission.DescriptionRtl", "Return to launch after completing the mission" },
                { "Mission.DescriptionTakeoff", "Fixed-wing takeoff candidate (local plan only)" },
                { "Mission.DescriptionSpeed", "Set mission cruise speed" },
                { "Mission.DescriptionSurveyWaypoint", "Survey-grid waypoint" },
                { "Mission.DescriptionRelativeLegFormat", "Relative leg {0}" },

                { "Validation.NoSpec", "GPT did not return parsable mission parameters." },
                { "Validation.NeedsClarification", "The mission information is incomplete and needs clarification." },
                { "Validation.NeedsClarificationFormat", "Clarification required: {0}" },
                { "Validation.SourceSummaryMissing", "The model did not provide an understanding of the mission sources; the candidate cannot be applied." },
                { "Validation.RequirementsMissing", "The model did not list mission requirements for operator confirmation." },
                { "Validation.HomeInvalid", "The planned Home in Mission Planner is invalid. Set a valid Home position first." },
                { "Validation.MissionTypeInvalid", "The model returned an unsupported mission type." },
                { "Validation.UnsupportedTemplate", "This objective cannot be converted into a supported deterministic mission template." },
                { "Validation.FieldCruiseAltitude", "Cruise altitude" },
                { "Validation.FieldCruiseSpeed", "Cruise speed" },
                { "Validation.FieldTakeoffAltitude", "Takeoff altitude" },
                { "Validation.CompletionMustRtl", "Only RTL is allowed as the mission completion action." },
                { "Validation.AiNoteFormat", "GPT note: {0}" },
                { "Validation.LocalOnlyWarning", "The candidate will not be uploaded and cannot arm, take off or change flight mode. Review it and write it manually using Mission Planner." },
                { "Validation.NoMissionItems", "The local compiler did not produce any mission items." },
                { "Validation.TooManyItemsFormat", "The mission item count exceeds the limit of {0}." },
                { "Validation.MissionHomeInvalid", "The mission range cannot be validated against an invalid Home position." },
                { "Validation.InvalidCoordinate", "The candidate mission contains an invalid coordinate or altitude." },
                { "Validation.WaypointTooFarFormat", "A candidate waypoint is outside the {0:0}-meter limit around Home." },
                { "Validation.SegmentDistanceInvalid", "A candidate leg distance could not be calculated." },
                { "Validation.NoWaypoints", "The candidate mission does not contain a valid waypoint." },
                { "Validation.RouteTooLongFormat", "The candidate route exceeds the {0:0}-meter total-length limit." },
                { "Validation.MustEndRtl", "The candidate mission must end with RETURN_TO_LAUNCH." },
                { "Validation.FieldLaneSpacing", "Lane spacing" },
                { "Validation.FieldGridAngle", "Grid angle" },
                { "Validation.SurveyPolygonMissing", "A survey requires a polygon with at least three vertices drawn in Flight Planner." },
                { "Validation.TooManyVerticesFormat", "The polygon vertex count exceeds the limit of {0}." },
                { "Validation.PolygonInvalid", "The drawn polygon contains an invalid coordinate." },
                { "Validation.PolygonTooFarFormat", "The drawn area is outside the {0:0}-meter limit around Home." },
                { "Validation.NoRelativeLegs", "A relative route requires at least one leg." },
                { "Validation.TooManyLegsFormat", "The relative-leg count exceeds the limit of {0}." },
                { "Validation.EmptyLegFormat", "Relative leg {0} is empty." },
                { "Validation.FieldLegBearingFormat", "Bearing for leg {0}" },
                { "Validation.FieldLegDistanceFormat", "Distance for leg {0}" },
                { "Validation.FieldLegAltitudeFormat", "Altitude for leg {0}" },
                { "Validation.RelativeRouteTooLongFormat", "The model's relative route exceeds the {0:0}-meter total-length limit." },
                { "Validation.NumberRangeFormat", "{0} must be between {1:0.###} and {2:0.###}." }
            };
        }

        private static IDictionary<string, string> CreateChinese()
        {
            return new Dictionary<string, string>(StringComparer.Ordinal)
            {
                { "App.Name", "AI 航点规划" },
                { "App.Title", "AI 航点规划 v2.0.0" },
                { "App.MenuTooltip", "根据自然语言任务生成经过本地校验的候选航点" },
                { "Safety.Banner", "安全边界：GPT 仅生成受限的候选任务。插件不会上传任务、改变飞行模式、解锁、起飞或发送 RC/PWM 指令。" },
                { "Nav.Chat", "对话" },
                { "Nav.Settings", "设置" },
                { "Nav.MissionReview", "任务复核" },
                { "Nav.Diagnostics", "诊断" },

                { "Chat.WelcomeTitle", "希望飞行器执行什么任务？" },
                { "Chat.WelcomeBody", "描述任务目标或添加参考文件。候选任务在您复核并应用前始终保留在本机。" },
                { "Chat.InputPlaceholder", "描述任务目标……" },
                { "Chat.NoMessages", "请先输入任务目标或添加参考文件。" },
                { "Chat.NewConversation", "新建对话" },
                { "Chat.ClearConversationPrompt", "清除当前对话和候选任务？" },
                { "Chat.FileCountFormat", "已添加 {0} 个文件" },
                { "Chat.UserLabel", "你" },
                { "Chat.AssistantLabel", "GPT" },
                { "Chat.SystemLabel", "系统" },
                { "Chat.TaskPrompt", "任务" },
                { "Chat.ThinkingLabel", "正在思考" },
                { "Chat.ReasoningSummaryLabel", "推理摘要" },
                { "Chat.ClarificationTitle", "还需要补充信息" },
                { "Chat.CandidateReadyTitle", "候选任务已就绪，请复核" },
                { "Chat.CandidateInvalidTitle", "候选任务未通过本地校验" },
                { "Chat.MessageFailed", "本次请求未能完成。" },
                { "Chat.EmptyObjective", "发送前请输入任务目标或添加文件。" },
                { "Chat.ReviewAction", "复核候选任务" },
                { "Chat.ViewDiagnostics", "查看请求诊断" },

                { "Status.Idle", "就绪" },
                { "Status.ReadingFiles", "正在读取附件……" },
                { "Status.PreparingRequest", "正在准备请求……" },
                { "Status.Connecting", "正在连接模型……" },
                { "Status.ReconnectingFormat", "正在重新连接（{0}/{1}）……" },
                { "Status.Thinking", "正在思考……" },
                { "Status.WaitingForModel", "正在等待模型……" },
                { "Status.Validating", "正在执行本地安全校验……" },
                { "Status.Compiling", "正在生成候选任务项……" },
                { "Status.ReadyForReview", "等待复核" },
                { "Status.NeedsClarification", "等待补充信息" },
                { "Status.Succeeded", "已完成" },
                { "Status.Failed", "请求失败" },
                { "Status.Cancelled", "请求已取消" },
                { "Status.TestingConnection", "正在测试连接……" },
                { "Status.ConnectionSucceeded", "连接成功" },
                { "Status.ConnectionFailed", "连接失败" },
                { "Status.Applying", "正在应用到本地飞行计划……" },
                { "Status.AppliedLocally", "已添加到本地飞行计划，尚未上传" },

                { "Button.Send", "发送" },
                { "Button.Stop", "停止" },
                { "Button.Attach", "添加文件" },
                { "Button.Remove", "移除" },
                { "Button.Clear", "清空" },
                { "Button.Settings", "设置" },
                { "Button.BackToChat", "返回对话" },
                { "Button.Close", "关闭" },
                { "Button.Save", "保存" },
                { "Button.Cancel", "取消" },
                { "Button.Confirm", "确认" },
                { "Button.TestConnection", "测试连接" },
                { "Button.SaveProfile", "保存组合" },
                { "Button.DeleteProfile", "删除组合" },
                { "Button.DeleteSavedKey", "删除已保存密钥" },
                { "Button.NewChat", "新建对话" },
                { "Button.ReviewMission", "复核任务" },
                { "Button.ApplyToPlan", "应用到飞行计划" },
                { "Button.Copy", "复制" },
                { "Button.CopyCurrentPage", "复制当前页" },
                { "Button.Retry", "重试" },

                { "Settings.Title", "设置" },
                { "Settings.Appearance", "外观与语言" },
                { "Settings.Language", "界面语言" },
                { "Settings.LanguageHelp", "插件退出时保存当前选择；未保存偏好时默认使用英语。" },
                { "Settings.Api", "API 连接" },
                { "Settings.Provider", "服务预设" },
                { "Settings.SavedProfile", "已保存组合" },
                { "Settings.BaseUrl", "API 基础地址" },
                { "Settings.Protocol", "API 协议" },
                { "Settings.Authentication", "鉴权方式" },
                { "Settings.ModelId", "模型 ID" },
                { "Settings.ProjectId", "OpenAI 项目 ID" },
                { "Settings.ApiKey", "API 密钥" },
                { "Settings.RememberKey", "保存到 Windows 凭据管理器" },
                { "Settings.Reasoning", "推理强度" },
                { "Settings.ReasoningHelp", "可用档位取决于所选模型和服务商。" },
                { "Settings.ConnectionActions", "连接操作" },
                { "Settings.CredentialStatus", "凭据状态" },
                { "Settings.Diagnostics", "诊断" },
                { "Settings.FileHandling", "文件处理" },
                { "Settings.ProfileName", "组合名称" },
                { "Settings.ProviderNote", "服务说明" },
                { "Settings.Saved", "设置已保存" },
                { "Settings.RestoredDefaults", "已恢复默认设置" },

                { "Protocol.Responses", "Responses API（/responses）" },
                { "Protocol.ChatCompletions", "Chat Completions（/chat/completions）" },
                { "Authentication.Bearer", "Bearer API 密钥" },
                { "Authentication.ApiKeyHeader", "api-key 请求头" },
                { "Authentication.None", "无需鉴权（本机网关）" },

                { "Reasoning.ProviderDefault", "服务商默认" },
                { "Reasoning.Low", "低" },
                { "Reasoning.Medium", "中" },
                { "Reasoning.High", "高" },
                { "Reasoning.VeryHigh", "极高" },
                { "Reasoning.Ultra", "ULTRA" },
                { "Reasoning.ProviderDefaultHelp", "不发送推理强度参数。" },
                { "Reasoning.Unsupported", "所选服务商或模型不支持该推理档位，请选择“服务商默认”或其他受支持档位。" },

                { "Attachment.Title", "附件" },
                { "Attachment.Empty", "尚未添加文件" },
                { "Attachment.FileName", "文件名" },
                { "Attachment.Type", "类型" },
                { "Attachment.Size", "大小" },
                { "Attachment.Status", "状态" },
                { "Attachment.Ready", "就绪" },
                { "Attachment.Reading", "正在读取文件" },
                { "Attachment.ImageWillSend", "图像将发送给模型" },
                { "Attachment.PdfNative", "PDF 将以原生文件发送" },
                { "Attachment.PdfText", "已提取 PDF 文本" },
                { "Attachment.DocxText", "已提取 DOCX 正文与表格文本" },
                { "Attachment.TextRead", "已读取文本" },
                { "Attachment.Removed", "附件已移除" },
                { "Attachment.LimitFormat", "最多 {0} 个文件，总计 {1}" },
                { "Attachment.SomeFailed", "部分文件未能添加。" },
                { "Attachment.SelectDialogTitle", "选择任务参考文件" },
                { "Attachment.DuplicateName", "两个附件不能使用相同的显示文件名。" },
                { "Attachment.NoUsedFiles", "模型没有确认使用任何已添加文件。请重新生成或检查文件支持情况。" },
                { "Attachment.UnrequestedFiles", "模型报告使用了未添加的文件。请重新生成。" },
                { "Attachment.UnknownUsedFileFormat", "模型报告了未知文件：{0}" },

                { "Mission.ReviewTitle", "复核候选任务" },
                { "Mission.Understanding", "模型理解" },
                { "Mission.Requirements", "待确认要求" },
                { "Mission.UsedFiles", "已使用文件" },
                { "Mission.NoFiles", "无" },
                { "Mission.CandidateSummary", "候选任务" },
                { "Mission.TemplateAndCountFormat", "模板：{0}；候选任务项：{1}" },
                { "Mission.Validation", "本地校验" },
                { "Mission.Items", "候选任务项" },
                { "Mission.Sequence", "序号" },
                { "Mission.Command", "命令" },
                { "Mission.Latitude", "纬度" },
                { "Mission.Longitude", "经度" },
                { "Mission.Altitude", "高度（米）" },
                { "Mission.Parameter1", "参数 1" },
                { "Mission.Parameter2", "参数 2" },
                { "Mission.Description", "说明" },
                { "Mission.ConfirmCheck", "我已复核并确认模型对任务及其要求的理解" },
                { "Mission.LocalOnlyNotice", "应用操作只会向本地 Flight Planner 添加任务行，不会把任务上传到飞控。" },
                { "Mission.ExistingItemsWarningFormat", "当前飞行计划已有 {0} 个任务项；候选项将追加而不会替换。" },
                { "Mission.ApplyConfirmFormat", "将 {0} 个候选任务项添加到本地 Flight Planner？" },
                { "Mission.Applied", "候选任务项已添加到本地 Flight Planner。手动写入任务前请逐项复核。" },
                { "Mission.RevalidationFailed", "任务状态已变化且重新校验失败；未应用任何内容。" },
                { "Mission.NoCandidate", "当前没有有效的候选任务。" },
                { "Mission.RelativeAltitudeRequired", "应用候选任务前，Flight Planner 高度模式必须为 Relative。" },
                { "Mission.StandardMissionRequired", "应用候选任务前，Flight Planner 任务类型必须为 Mission。" },
                { "Mission.AppendFailedFormat", "候选任务无法追加；本次操作已添加的行已撤回。{0}" },
                { "Mission.CommandChanged", "Mission Planner 在追加候选项时修改了命令。请关闭自动样条转换后重试。" },

                { "Validation.Passed", "本地校验通过。" },
                { "Validation.ErrorPrefix", "错误：{0}" },
                { "Validation.WarningPrefix", "警告：{0}" },
                { "Validation.InfoPrefix", "提示：{0}" },

                { "Diagnostics.Title", "模型返回数据与请求诊断" },
                { "Diagnostics.RequestMetadata", "请求元数据" },
                { "Diagnostics.RawResponse", "模型原始响应" },
                { "Diagnostics.StructuredData", "结构化任务数据" },
                { "Diagnostics.DiagnosticInfo", "诊断信息" },
                { "Diagnostics.NoRawResponse", "服务没有返回响应正文。" },
                { "Diagnostics.NoStructuredData", "尚未提取出结构化任务数据。" },
                { "Diagnostics.NoError", "本次请求没有记录错误。" },
                { "Diagnostics.RequestedAtFormat", "请求时间：{0}" },
                { "Diagnostics.RequestFormat", "请求：{0} {1}" },
                { "Diagnostics.ProtocolModelFormat", "协议 / 模型：{0} / {1}" },
                { "Diagnostics.HttpStatusFormat", "HTTP 状态：{0}" },
                { "Diagnostics.NoHttpResponse", "未收到 HTTP 响应" },
                { "Diagnostics.RequestIdFormat", "请求 ID：{0}" },
                { "Diagnostics.AttemptsFormat", "连接尝试：{0}" },
                { "Diagnostics.ReconnectsFormat", "自动重连：{0}" },

                { "Api.CredentialNone", "无需插件密钥；凭据由本机网关管理。" },
                { "Api.CredentialMissing", "未发现可用 API 密钥。" },
                { "Api.CredentialFoundFormat", "已发现来自 {0} 的凭据；密钥内容不显示。" },
                { "Api.CredentialReadFailedFormat", "凭据检查失败：{0}" },
                { "Api.SourceSession", "当前会话" },
                { "Api.SourceEnvironment", "OPENAI_API_KEY 环境变量" },
                { "Api.SourceWindows", "Windows 凭据管理器" },
                { "Api.SourceNone", "无" },
                { "Api.ProfileMissing", "请先选择已保存的连接组合。" },
                { "Api.KeySaved", "密钥已保存到 Windows 凭据管理器。" },
                { "Api.KeyDeleted", "已删除保存的密钥。" },
                { "Api.NoSavedKey", "未找到已保存的密钥。" },
                { "Api.ProfileLoadedFormat", "已加载组合：{0}" },
                { "Api.ProfileSavedFormat", "已保存组合：{0}" },
                { "Api.ProfileDeleted", "组合已删除" },
                { "Api.ProfileNamePrompt", "请输入当前连接组合的名称。" },
                { "Api.TestSuccessFormat", "连接成功；凭据来源：{0}" },
                { "Api.RemoteHttpsRequired", "远程接口必须使用 HTTPS；只有本机回环地址可以使用明文 HTTP。" },

                { "TaskSuggestions.Title", "尝试一个任务" },
                { "TaskSuggestions.RelativeRoute", "从计划 Home 按相对航段飞行，然后返航。" },
                { "TaskSuggestions.SurveyPolygon", "测绘 Flight Planner 中已绘制的多边形，然后返航。" },
                { "TaskSuggestions.FromFile", "读取附件中的任务说明并指出缺失信息。" },

                { "Dialog.Information", "提示" },
                { "Dialog.Warning", "警告" },
                { "Dialog.Error", "错误" },
                { "Dialog.ConfirmApply", "确认修改本地任务" },
                { "Dialog.ConfirmDeleteProfile", "删除所选连接组合？" },
                { "Dialog.ConfirmClear", "清除对话" },

                { "ProviderName.CcSwitch", "CC Switch（本机）" },
                { "ProviderName.OpenAi", "OpenAI" },
                { "ProviderName.OpenRouter", "OpenRouter" },
                { "ProviderName.LiteLlm", "LiteLLM 代理（本机）" },
                { "ProviderName.LmStudio", "LM Studio（本机）" },
                { "ProviderName.Ollama", "Ollama（本机）" },
                { "ProviderName.NewApi", "New API / One API" },
                { "ProviderName.Azure", "Azure OpenAI" },
                { "ProviderName.Custom", "自定义 OpenAI 兼容 API" },
                { "ProviderNote.CcSwitch", "请先启动 CC Switch 本地代理并开启路由；上游密钥或 OAuth 会话由 CC Switch 管理。" },
                { "ProviderNote.OpenAi", "请使用 OpenAI API 密钥；ChatGPT 或 Codex 登录本身不是 API 密钥。" },
                { "ProviderNote.OpenRouter", "请使用 OpenRouter 密钥以及账户支持的模型 ID。" },
                { "ProviderNote.LiteLlm", "适用于本机 LiteLLM 代理；代理未设置密钥时请选择无鉴权。" },
                { "ProviderNote.LmStudio", "请在 LM Studio 中加载模型并启动本地服务器。" },
                { "ProviderNote.Ollama", "请先启动 Ollama，并填写已在本机安装的模型 ID。" },
                { "ProviderNote.NewApi", "请将示例主机替换为实际网关；兼容性取决于其 OpenAI 协议实现。" },
                { "ProviderNote.Azure", "请使用资源的 v1 基础地址和 api-key 请求头；模型 ID 通常是部署名称。" },
                { "ProviderNote.Custom", "请编辑基础地址、协议、鉴权和模型。插件不直接处理原生 Anthropic 或 Gemini 协议。" },

                { "Attachment.FilterMissionReferences", "任务参考文件" },
                { "Attachment.FilterDocuments", "PDF 与 Office 文件" },
                { "Attachment.FilterImages", "图像文件" },
                { "Attachment.FilterTextData", "文本与数据文件" },
                { "Attachment.FilterAllFiles", "所有文件" },
                { "Attachment.DocumentNative", "文档将通过 Responses API 以原生文件发送" },
                { "Attachment.ErrorPathRequired", "文件路径不能为空。" },
                { "Attachment.ErrorNotFound", "找不到所选文件。" },
                { "Attachment.ErrorEmptyFileFormat", "不能添加空文件：{0}" },
                { "Attachment.ErrorFileTooLargeFormat", "单个文件不能超过 12 MB：{0}" },
                { "Attachment.ErrorTooManyFilesFormat", "最多只能添加 {0} 个文件。" },
                { "Attachment.ErrorTotalSize", "附件总大小不能超过 24 MB。" },
                { "Attachment.ErrorUnsupportedTypeFormat", "暂不支持该文件类型：{0}。可使用 PDF、Word/RTF/ODT、PowerPoint、Excel、PNG/JPEG/WebP/GIF 或常见文本/数据文件。" },
                { "Attachment.ErrorExtractedTextTotal", "附件提取文本总量不能超过 120,000 个字符，请精简或拆分资料。" },
                { "Attachment.ErrorCountLimit", "附件数量超过安全上限。" },
                { "Attachment.ErrorTotalLimit", "附件总大小超过安全上限。" },
                { "Attachment.ErrorTextLimit", "附件提取文本超过安全上限。" },
                { "Attachment.ErrorChatNativeUnsupported", "Chat Completions 不能直接发送该原生文件，且本地没有可用的提取文本。请改用 Responses API，或先将文件转为可读文本；扫描 PDF 需要 OCR。" },
                { "Attachment.ErrorImageTooLargeFormat", "单张图像不能超过 8 MB：{0}" },
                { "Attachment.ErrorPdfReadFormat", "无法读取 PDF，文件可能已加密或损坏：{0}。{1}" },
                { "Attachment.ErrorDocxXmlMissing", "DOCX 中缺少 word/document.xml。" },
                { "Attachment.ErrorDocxReadFormat", "无法读取 DOCX，文件可能已加密或损坏：{0}。{1}" },
                { "Attachment.ErrorDocxEmptyFormat", "DOCX 中没有可读取的正文文字：{0}" },
                { "Attachment.ErrorBinaryTextFormat", "文件看起来是二进制内容，无法作为文本读取：{0}" },
                { "Attachment.ErrorTextEmptyFormat", "文本文件没有可读取内容：{0}" },

                { "Api.ProfileNameTooLong", "连接组合名称不能超过 80 个字符。" },
                { "Api.ProfileEndpointModelRequired", "请先填写 API 基础地址和模型 ID。" },
                { "Api.ErrorModelRequired", "模型 ID 不能为空。" },
                { "Api.ErrorKeyRequired", "当前鉴权方式需要 API 密钥。" },
                { "Api.ErrorReasoningInvalid", "推理强度设置无效。" },
                { "Api.ErrorBaseUrlInvalid", "API 基础地址必须是完整的 HTTP 或 HTTPS 地址。" },
                { "Api.ErrorBaseUrlQuery", "API 基础地址不能包含查询参数或片段。" },
                { "Api.ErrorRemoteHttp", "仅本机回环地址允许使用明文 HTTP；远程 API 必须使用 HTTPS。" },
                { "Api.ErrorObjectiveRequired", "任务目标不能为空。" },
                { "Api.ErrorResponseParseFormat", "模型响应解析失败：{0}" },
                { "Api.ErrorStructuredParseFormat", "结构化任务 JSON 反序列化失败：{0}" },
                { "Api.ErrorStructuredEmpty", "AI API 返回的结构化结果为空。" },
                { "Api.ErrorEmptyResponse", "AI API 返回了空响应。" },
                { "Api.ErrorResponseInvalid", "无法解析 AI API 响应。" },
                { "Api.ErrorApiReturnedFormat", "AI API 返回错误：{0}" },
                { "Api.ErrorResponsesOutputMissing", "Responses API 响应缺少 output 字段。" },
                { "Api.ErrorRefusalFormat", "模型拒绝处理该目标：{0}" },
                { "Api.ErrorResponsesIncompleteFormat", "Responses API 响应未完成：{0}" },
                { "Api.ErrorResponsesTextMissing", "Responses API 响应中没有可用的结构化文本。" },
                { "Api.ErrorChatResponseInvalid", "无法解析 Chat Completions 响应。" },
                { "Api.ErrorChatChoicesMissing", "Chat Completions 响应缺少 choices 字段。" },
                { "Api.ErrorChatTextMissing", "Chat Completions 响应中没有可用的结构化文本。" },
                { "Api.ErrorNoServiceDetails", "服务未返回错误详情。" },
                { "Api.ErrorUnknown", "未知错误" },
                { "Api.ConnectionRecoveredFormat", "连接已恢复，共尝试 {0} 次。" },
                { "Api.RequestIdSuffixFormat", "（请求 ID：{0}）" },
                { "Api.HttpFailureFormat", "AI API 请求失败，HTTP {0}：{1}{2}" },
                { "Api.ErrorTimeoutRetriesExhausted", "请求超过 90 秒超时，且自动重连已用尽。" },
                { "Api.ReconnectingFormat", "临时连接问题，正在自动重连：第 {0}/{1} 次尝试，等待 {2} 毫秒。" },
                { "Api.TransportNoDetails", "API 请求失败，但没有可用的异常详情。" },
                { "Api.ServiceName", "API 服务" },
                { "Api.TransportLocalRefusedFormat", "无法连接本机 API 代理 {0}。请启动代理或 CC Switch 路由，并核对基础地址和端口。底层错误：{1}" },
                { "Api.TransportLocalFormat", "无法访问本机 API 代理 {0}。请检查代理状态、基础地址和端口。底层错误：{1}" },
                { "Api.TransportRemoteFormat", "无法连接 API 服务 {0}。请检查网络、基础地址、TLS 和代理设置。底层错误：{1}" },

                { "Mission.CompilationFailedFormat", "本地任务编译失败：{0}" },
                { "Mission.DescriptionRtl", "任务完成后返航" },
                { "Mission.DescriptionTakeoff", "固定翼任务起飞项（仅加入本地任务表）" },
                { "Mission.DescriptionSpeed", "设置任务巡航速度" },
                { "Mission.DescriptionSurveyWaypoint", "区域巡视网格航点" },
                { "Mission.DescriptionRelativeLegFormat", "相对航段 {0}" },

                { "Validation.NoSpec", "GPT 未返回可解析的任务参数。" },
                { "Validation.NeedsClarification", "任务信息不足，需要补充说明。" },
                { "Validation.NeedsClarificationFormat", "需要补充说明：{0}" },
                { "Validation.SourceSummaryMissing", "模型未提供对任务资料的理解摘要，不能进入应用流程。" },
                { "Validation.RequirementsMissing", "模型未列出需要操作员确认的任务要求。" },
                { "Validation.HomeInvalid", "Mission Planner 的计划 Home 无效，请先设置正确的 Home 位置。" },
                { "Validation.MissionTypeInvalid", "模型返回了不受支持的任务类型。" },
                { "Validation.UnsupportedTemplate", "当前版本无法把该目标转换为受支持的确定性任务模板。" },
                { "Validation.FieldCruiseAltitude", "巡航高度" },
                { "Validation.FieldCruiseSpeed", "巡航速度" },
                { "Validation.FieldTakeoffAltitude", "起飞高度" },
                { "Validation.CompletionMustRtl", "当前版本只允许 RTL 作为任务结束动作。" },
                { "Validation.AiNoteFormat", "GPT 提示：{0}" },
                { "Validation.LocalOnlyWarning", "候选任务不会自动上传、解锁、起飞或改变飞行模式；应用后仍需人工复核并通过 Mission Planner 手动写入。" },
                { "Validation.NoMissionItems", "本地任务编译器没有生成任何任务项。" },
                { "Validation.TooManyItemsFormat", "任务项数量超过上限 {0}。" },
                { "Validation.MissionHomeInvalid", "无法依据无效 Home 校验任务范围。" },
                { "Validation.InvalidCoordinate", "候选任务包含无效经纬度或高度。" },
                { "Validation.WaypointTooFarFormat", "候选航点超出 Home 周围 {0:0} 米限制。" },
                { "Validation.SegmentDistanceInvalid", "无法计算候选航段距离。" },
                { "Validation.NoWaypoints", "候选任务不包含有效航点。" },
                { "Validation.RouteTooLongFormat", "候选航线总长度超过 {0:0} 米限制。" },
                { "Validation.MustEndRtl", "候选任务必须以 RETURN_TO_LAUNCH 结束。" },
                { "Validation.FieldLaneSpacing", "航线间距" },
                { "Validation.FieldGridAngle", "网格角度" },
                { "Validation.SurveyPolygonMissing", "区域巡视需要先在 Flight Planner 地图上绘制至少三个顶点的多边形。" },
                { "Validation.TooManyVerticesFormat", "多边形顶点数量超过上限 {0}。" },
                { "Validation.PolygonInvalid", "绘制的多边形包含无效坐标。" },
                { "Validation.PolygonTooFarFormat", "绘制区域超出 Home 周围 {0:0} 米限制。" },
                { "Validation.NoRelativeLegs", "相对航线至少需要一个航段。" },
                { "Validation.TooManyLegsFormat", "相对航段数量超过上限 {0}。" },
                { "Validation.EmptyLegFormat", "第 {0} 个航段为空。" },
                { "Validation.FieldLegBearingFormat", "第 {0} 航段方位角" },
                { "Validation.FieldLegDistanceFormat", "第 {0} 航段距离" },
                { "Validation.FieldLegAltitudeFormat", "第 {0} 航段高度" },
                { "Validation.RelativeRouteTooLongFormat", "模型给出的相对航段总长超过 {0:0} 米限制。" },
                { "Validation.NumberRangeFormat", "{0}必须在 {1:0.###} 至 {2:0.###} 之间。" }
            };
        }

        private static IDictionary<string, string> CreateRussian()
        {
            return new Dictionary<string, string>(StringComparer.Ordinal)
            {
                { "App.Name", "Планировщик маршрута ИИ" },
                { "App.Title", "Планировщик маршрута ИИ v2.0.0" },
                { "App.MenuTooltip", "Создание локально проверенных маршрутных точек по описанию задачи" },
                { "Safety.Banner", "Граница безопасности: GPT создаёт только ограниченный проект задания. Плагин не загружает задание, не меняет режим полёта, не выполняет разблокировку или взлёт и не отправляет команды RC/PWM." },
                { "Nav.Chat", "Диалог" },
                { "Nav.Settings", "Настройки" },
                { "Nav.MissionReview", "Проверка задания" },
                { "Nav.Diagnostics", "Диагностика" },

                { "Chat.WelcomeTitle", "Какую задачу должен выполнить аппарат?" },
                { "Chat.WelcomeBody", "Опишите цель задания или приложите справочные файлы. Проект останется локальным, пока вы не проверите и не примените его." },
                { "Chat.InputPlaceholder", "Опишите цель задания..." },
                { "Chat.NoMessages", "Начните с цели задания или справочного файла." },
                { "Chat.NewConversation", "Новый диалог" },
                { "Chat.ClearConversationPrompt", "Очистить текущий диалог и проект задания?" },
                { "Chat.FileCountFormat", "Прикреплено файлов: {0}" },
                { "Chat.UserLabel", "Вы" },
                { "Chat.AssistantLabel", "GPT" },
                { "Chat.SystemLabel", "Система" },
                { "Chat.TaskPrompt", "Задача" },
                { "Chat.ThinkingLabel", "Обдумывание" },
                { "Chat.ReasoningSummaryLabel", "Сводка рассуждений" },
                { "Chat.ClarificationTitle", "Требуются дополнительные сведения" },
                { "Chat.CandidateReadyTitle", "Проект задания готов к проверке" },
                { "Chat.CandidateInvalidTitle", "Проект задания не прошёл локальную проверку" },
                { "Chat.MessageFailed", "Не удалось выполнить запрос." },
                { "Chat.EmptyObjective", "Перед отправкой введите цель задания или приложите файл." },
                { "Chat.ReviewAction", "Проверить проект задания" },
                { "Chat.ViewDiagnostics", "Открыть диагностику запроса" },

                { "Status.Idle", "Готово" },
                { "Status.ReadingFiles", "Чтение вложений..." },
                { "Status.PreparingRequest", "Подготовка запроса..." },
                { "Status.Connecting", "Подключение к модели..." },
                { "Status.ReconnectingFormat", "Повторное подключение ({0}/{1})..." },
                { "Status.Thinking", "Обдумывание..." },
                { "Status.WaitingForModel", "Ожидание ответа модели..." },
                { "Status.Validating", "Локальная проверка безопасности..." },
                { "Status.Compiling", "Формирование элементов задания..." },
                { "Status.ReadyForReview", "Готово к проверке" },
                { "Status.NeedsClarification", "Ожидание уточнения" },
                { "Status.Succeeded", "Завершено" },
                { "Status.Failed", "Ошибка запроса" },
                { "Status.Cancelled", "Запрос отменён" },
                { "Status.TestingConnection", "Проверка подключения..." },
                { "Status.ConnectionSucceeded", "Подключение успешно" },
                { "Status.ConnectionFailed", "Ошибка подключения" },
                { "Status.Applying", "Добавление в локальный план полёта..." },
                { "Status.AppliedLocally", "Добавлено в локальный план; загрузка не выполнялась" },

                { "Button.Send", "Отправить" },
                { "Button.Stop", "Остановить" },
                { "Button.Attach", "Прикрепить файлы" },
                { "Button.Remove", "Удалить" },
                { "Button.Clear", "Очистить" },
                { "Button.Settings", "Настройки" },
                { "Button.BackToChat", "Вернуться к диалогу" },
                { "Button.Close", "Закрыть" },
                { "Button.Save", "Сохранить" },
                { "Button.Cancel", "Отмена" },
                { "Button.Confirm", "Подтвердить" },
                { "Button.TestConnection", "Проверить подключение" },
                { "Button.SaveProfile", "Сохранить профиль" },
                { "Button.DeleteProfile", "Удалить профиль" },
                { "Button.DeleteSavedKey", "Удалить сохранённый ключ" },
                { "Button.NewChat", "Новый диалог" },
                { "Button.ReviewMission", "Проверить задание" },
                { "Button.ApplyToPlan", "Добавить в план полёта" },
                { "Button.Copy", "Копировать" },
                { "Button.CopyCurrentPage", "Копировать текущую вкладку" },
                { "Button.Retry", "Повторить" },

                { "Settings.Title", "Настройки" },
                { "Settings.Appearance", "Оформление и язык" },
                { "Settings.Language", "Язык интерфейса" },
                { "Settings.LanguageHelp", "Выбранный язык сохраняется при закрытии плагина. Если настройка отсутствует, используется английский язык." },
                { "Settings.Api", "Подключение API" },
                { "Settings.Provider", "Профиль поставщика" },
                { "Settings.SavedProfile", "Сохранённый профиль" },
                { "Settings.BaseUrl", "Базовый URL API" },
                { "Settings.Protocol", "Протокол API" },
                { "Settings.Authentication", "Аутентификация" },
                { "Settings.ModelId", "Идентификатор модели" },
                { "Settings.ProjectId", "Идентификатор проекта OpenAI" },
                { "Settings.ApiKey", "Ключ API" },
                { "Settings.RememberKey", "Сохранить в диспетчере учётных данных Windows" },
                { "Settings.Reasoning", "Глубина рассуждений" },
                { "Settings.ReasoningHelp", "Доступность уровней зависит от выбранной модели и поставщика." },
                { "Settings.ConnectionActions", "Действия с подключением" },
                { "Settings.CredentialStatus", "Состояние учётных данных" },
                { "Settings.Diagnostics", "Диагностика" },
                { "Settings.FileHandling", "Обработка файлов" },
                { "Settings.ProfileName", "Имя профиля" },
                { "Settings.ProviderNote", "Сведения о поставщике" },
                { "Settings.Saved", "Настройки сохранены" },
                { "Settings.RestoredDefaults", "Восстановлены настройки по умолчанию" },

                { "Protocol.Responses", "Responses API (/responses)" },
                { "Protocol.ChatCompletions", "Chat Completions (/chat/completions)" },
                { "Authentication.Bearer", "Ключ API Bearer" },
                { "Authentication.ApiKeyHeader", "Заголовок api-key" },
                { "Authentication.None", "Без аутентификации (локальный шлюз)" },

                { "Reasoning.ProviderDefault", "По умолчанию поставщика" },
                { "Reasoning.Low", "Низкая" },
                { "Reasoning.Medium", "Средняя" },
                { "Reasoning.High", "Высокая" },
                { "Reasoning.VeryHigh", "Очень высокая" },
                { "Reasoning.Ultra", "ULTRA" },
                { "Reasoning.ProviderDefaultHelp", "Не отправлять параметр глубины рассуждений." },
                { "Reasoning.Unsupported", "Выбранный поставщик или модель не поддерживает этот уровень. Выберите значение поставщика по умолчанию или другой поддерживаемый уровень." },

                { "Attachment.Title", "Вложения" },
                { "Attachment.Empty", "Нет вложений" },
                { "Attachment.FileName", "Имя файла" },
                { "Attachment.Type", "Тип" },
                { "Attachment.Size", "Размер" },
                { "Attachment.Status", "Состояние" },
                { "Attachment.Ready", "Готово" },
                { "Attachment.Reading", "Чтение файла" },
                { "Attachment.ImageWillSend", "Изображение будет отправлено модели" },
                { "Attachment.PdfNative", "PDF будет отправлен как исходный файл" },
                { "Attachment.PdfText", "Текст PDF извлечён" },
                { "Attachment.DocxText", "Извлечены текст и таблицы DOCX" },
                { "Attachment.TextRead", "Текст прочитан" },
                { "Attachment.Removed", "Вложение удалено" },
                { "Attachment.LimitFormat", "Не более {0} файлов, общий объём {1}" },
                { "Attachment.SomeFailed", "Не удалось добавить некоторые файлы." },
                { "Attachment.SelectDialogTitle", "Выберите справочные файлы задания" },
                { "Attachment.DuplicateName", "Два вложения не могут иметь одинаковое отображаемое имя." },
                { "Attachment.NoUsedFiles", "Модель не подтвердила использование вложенных файлов. Повторите запрос или проверьте поддержку файлов." },
                { "Attachment.UnrequestedFiles", "Модель сообщила о файле, который не был прикреплён. Повторите запрос." },
                { "Attachment.UnknownUsedFileFormat", "Модель сообщила о неизвестном файле: {0}" },

                { "Mission.ReviewTitle", "Проверка проекта задания" },
                { "Mission.Understanding", "Понимание модели" },
                { "Mission.Requirements", "Требования для подтверждения" },
                { "Mission.UsedFiles", "Использованные файлы" },
                { "Mission.NoFiles", "Нет" },
                { "Mission.CandidateSummary", "Проект задания" },
                { "Mission.TemplateAndCountFormat", "Шаблон: {0}; элементов задания: {1}" },
                { "Mission.Validation", "Локальная проверка" },
                { "Mission.Items", "Элементы проекта задания" },
                { "Mission.Sequence", "№" },
                { "Mission.Command", "Команда" },
                { "Mission.Latitude", "Широта" },
                { "Mission.Longitude", "Долгота" },
                { "Mission.Altitude", "Высота (м)" },
                { "Mission.Parameter1", "Параметр 1" },
                { "Mission.Parameter2", "Параметр 2" },
                { "Mission.Description", "Описание" },
                { "Mission.ConfirmCheck", "Я проверил и подтверждаю понимание модели и требования задания" },
                { "Mission.LocalOnlyNotice", "Применение добавляет строки только в локальный Flight Planner и не загружает задание в полётный контроллер." },
                { "Mission.ExistingItemsWarningFormat", "План полёта уже содержит элементов: {0}. Новые элементы будут добавлены без замены существующих." },
                { "Mission.ApplyConfirmFormat", "Добавить элементов проекта в локальный Flight Planner: {0}?" },
                { "Mission.Applied", "Элементы проекта добавлены в локальный Flight Planner. Проверьте их перед ручной записью задания." },
                { "Mission.RevalidationFailed", "Состояние задания изменилось, и повторная локальная проверка завершилась ошибкой. Изменения не применены." },
                { "Mission.NoCandidate", "Нет допустимого проекта задания." },
                { "Mission.RelativeAltitudeRequired", "Перед применением проекта режим высоты Flight Planner должен быть Relative." },
                { "Mission.StandardMissionRequired", "Перед применением проекта тип задания Flight Planner должен быть Mission." },
                { "Mission.AppendFailedFormat", "Проект не удалось добавить; строки, добавленные этой операцией, отменены. {0}" },
                { "Mission.CommandChanged", "Mission Planner изменил команду при добавлении кандидата. Отключите автоматическое преобразование в сплайн и повторите попытку." },

                { "Validation.Passed", "Локальная проверка пройдена." },
                { "Validation.ErrorPrefix", "Ошибка: {0}" },
                { "Validation.WarningPrefix", "Предупреждение: {0}" },
                { "Validation.InfoPrefix", "Сведения: {0}" },

                { "Diagnostics.Title", "Ответ модели и диагностика запроса" },
                { "Diagnostics.RequestMetadata", "Метаданные запроса" },
                { "Diagnostics.RawResponse", "Исходный ответ модели" },
                { "Diagnostics.StructuredData", "Структурированные данные задания" },
                { "Diagnostics.DiagnosticInfo", "Диагностические сведения" },
                { "Diagnostics.NoRawResponse", "Служба не вернула тело ответа." },
                { "Diagnostics.NoStructuredData", "Структурированные данные задания не извлечены." },
                { "Diagnostics.NoError", "Для этого запроса ошибки не зарегистрированы." },
                { "Diagnostics.RequestedAtFormat", "Время запроса: {0}" },
                { "Diagnostics.RequestFormat", "Запрос: {0} {1}" },
                { "Diagnostics.ProtocolModelFormat", "Протокол / модель: {0} / {1}" },
                { "Diagnostics.HttpStatusFormat", "Состояние HTTP: {0}" },
                { "Diagnostics.NoHttpResponse", "Ответ HTTP не получен" },
                { "Diagnostics.RequestIdFormat", "Идентификатор запроса: {0}" },
                { "Diagnostics.AttemptsFormat", "Попыток подключения: {0}" },
                { "Diagnostics.ReconnectsFormat", "Автоматических переподключений: {0}" },

                { "Api.CredentialNone", "Ключ плагина не требуется: учётными данными управляет локальный шлюз." },
                { "Api.CredentialMissing", "Подходящий ключ API не найден." },
                { "Api.CredentialFoundFormat", "Доступны учётные данные из источника «{0}»; ключ скрыт." },
                { "Api.CredentialReadFailedFormat", "Ошибка проверки учётных данных: {0}" },
                { "Api.SourceSession", "Текущий сеанс" },
                { "Api.SourceEnvironment", "Переменная среды OPENAI_API_KEY" },
                { "Api.SourceWindows", "Диспетчер учётных данных Windows" },
                { "Api.SourceNone", "Нет" },
                { "Api.ProfileMissing", "Сначала выберите сохранённый профиль подключения." },
                { "Api.KeySaved", "Ключ сохранён в диспетчере учётных данных Windows." },
                { "Api.KeyDeleted", "Сохранённый ключ удалён." },
                { "Api.NoSavedKey", "Сохранённый ключ не найден." },
                { "Api.ProfileLoadedFormat", "Загружен профиль: {0}" },
                { "Api.ProfileSavedFormat", "Сохранён профиль: {0}" },
                { "Api.ProfileDeleted", "Профиль удалён" },
                { "Api.ProfileNamePrompt", "Введите имя профиля подключения." },
                { "Api.TestSuccessFormat", "Подключение успешно; источник учётных данных: {0}" },
                { "Api.RemoteHttpsRequired", "Удалённые конечные точки должны использовать HTTPS. Обычный HTTP разрешён только для локального loopback-адреса." },

                { "TaskSuggestions.Title", "Пример задания" },
                { "TaskSuggestions.RelativeRoute", "Пролететь относительный маршрут от запланированной точки Home, затем вернуться к точке старта." },
                { "TaskSuggestions.SurveyPolygon", "Выполнить съёмку полигона, нарисованного в Flight Planner, затем вернуться к точке старта." },
                { "TaskSuggestions.FromFile", "Прочитать описание задания во вложении и указать недостающие сведения." },

                { "Dialog.Information", "Сведения" },
                { "Dialog.Warning", "Предупреждение" },
                { "Dialog.Error", "Ошибка" },
                { "Dialog.ConfirmApply", "Подтверждение изменения локального задания" },
                { "Dialog.ConfirmDeleteProfile", "Удалить выбранный профиль подключения?" },
                { "Dialog.ConfirmClear", "Очистка диалога" },

                { "ProviderName.CcSwitch", "CC Switch (локальный)" },
                { "ProviderName.OpenAi", "OpenAI" },
                { "ProviderName.OpenRouter", "OpenRouter" },
                { "ProviderName.LiteLlm", "Прокси LiteLLM (локальный)" },
                { "ProviderName.LmStudio", "LM Studio (локальный)" },
                { "ProviderName.Ollama", "Ollama (локальный)" },
                { "ProviderName.NewApi", "New API / One API" },
                { "ProviderName.Azure", "Azure OpenAI" },
                { "ProviderName.Custom", "Пользовательский OpenAI-совместимый API" },
                { "ProviderNote.CcSwitch", "Сначала запустите локальный прокси и маршрут CC Switch; ключом или сеансом OAuth вышестоящего сервиса управляет CC Switch." },
                { "ProviderNote.OpenAi", "Используйте ключ OpenAI API; вход в ChatGPT или Codex сам по себе не является ключом API." },
                { "ProviderNote.OpenRouter", "Используйте ключ OpenRouter и идентификатор модели, доступной вашей учётной записи." },
                { "ProviderNote.LiteLlm", "Для локального прокси LiteLLM; выберите режим без аутентификации, если ключ прокси не задан." },
                { "ProviderNote.LmStudio", "Загрузите модель в LM Studio и запустите локальный сервер." },
                { "ProviderNote.Ollama", "Запустите Ollama и укажите идентификатор уже установленной локальной модели." },
                { "ProviderNote.NewApi", "Замените пример адреса своим шлюзом; совместимость зависит от реализации протокола OpenAI." },
                { "ProviderNote.Azure", "Используйте базовый URL v1 ресурса и заголовок api-key; идентификатор модели обычно совпадает с именем развёртывания." },
                { "ProviderNote.Custom", "Настройте базовый URL, протокол, аутентификацию и модель. Исходные протоколы Anthropic и Gemini напрямую не поддерживаются." },

                { "Attachment.FilterMissionReferences", "Справочные файлы задания" },
                { "Attachment.FilterDocuments", "Файлы PDF и Office" },
                { "Attachment.FilterImages", "Изображения" },
                { "Attachment.FilterTextData", "Текстовые файлы и данные" },
                { "Attachment.FilterAllFiles", "Все файлы" },
                { "Attachment.DocumentNative", "Документ будет отправлен как исходный файл Responses API" },
                { "Attachment.ErrorPathRequired", "Необходимо указать путь к файлу." },
                { "Attachment.ErrorNotFound", "Выбранный файл не найден." },
                { "Attachment.ErrorEmptyFileFormat", "Нельзя прикрепить пустой файл: {0}" },
                { "Attachment.ErrorFileTooLargeFormat", "Размер одного файла не должен превышать 12 МБ: {0}" },
                { "Attachment.ErrorTooManyFilesFormat", "Можно прикрепить не более {0} файлов." },
                { "Attachment.ErrorTotalSize", "Общий размер вложений не должен превышать 24 МБ." },
                { "Attachment.ErrorUnsupportedTypeFormat", "Этот тип файла не поддерживается: {0}. Используйте PDF, Word/RTF/ODT, PowerPoint, Excel, PNG/JPEG/WebP/GIF либо распространённый текстовый формат или формат данных." },
                { "Attachment.ErrorExtractedTextTotal", "Объём извлечённого текста вложений не должен превышать 120 000 символов. Сократите или разделите материалы." },
                { "Attachment.ErrorCountLimit", "Количество вложений превышает безопасный предел." },
                { "Attachment.ErrorTotalLimit", "Общий размер вложений превышает безопасный предел." },
                { "Attachment.ErrorTextLimit", "Объём извлечённого текста превышает безопасный предел." },
                { "Attachment.ErrorChatNativeUnsupported", "Chat Completions не может отправить этот исходный файл, а локально извлечённый текст отсутствует. Используйте Responses API или преобразуйте файл в читаемый текст; для сканированного PDF требуется OCR." },
                { "Attachment.ErrorImageTooLargeFormat", "Размер изображения не должен превышать 8 МБ: {0}" },
                { "Attachment.ErrorPdfReadFormat", "Не удалось прочитать PDF; возможно, файл зашифрован или повреждён: {0}. {1}" },
                { "Attachment.ErrorDocxXmlMissing", "В DOCX отсутствует word/document.xml." },
                { "Attachment.ErrorDocxReadFormat", "Не удалось прочитать DOCX; возможно, файл зашифрован или повреждён: {0}. {1}" },
                { "Attachment.ErrorDocxEmptyFormat", "В DOCX нет читаемого основного текста: {0}" },
                { "Attachment.ErrorBinaryTextFormat", "Файл содержит двоичные данные и не может быть прочитан как текст: {0}" },
                { "Attachment.ErrorTextEmptyFormat", "В текстовом файле нет читаемого содержимого: {0}" },

                { "Api.ProfileNameTooLong", "Имя профиля не должно превышать 80 символов." },
                { "Api.ProfileEndpointModelRequired", "Сначала укажите базовый URL API и идентификатор модели." },
                { "Api.ErrorModelRequired", "Необходимо указать идентификатор модели." },
                { "Api.ErrorKeyRequired", "Для выбранного способа аутентификации требуется ключ API." },
                { "Api.ErrorReasoningInvalid", "Задано недопустимое значение глубины рассуждений." },
                { "Api.ErrorBaseUrlInvalid", "Базовый URL API должен быть полным адресом HTTP или HTTPS." },
                { "Api.ErrorBaseUrlQuery", "Базовый URL API не должен содержать строку запроса или фрагмент." },
                { "Api.ErrorRemoteHttp", "Обычный HTTP разрешён только для локального loopback-адреса; удалённый API должен использовать HTTPS." },
                { "Api.ErrorObjectiveRequired", "Необходимо указать цель задания." },
                { "Api.ErrorResponseParseFormat", "Не удалось разобрать ответ модели: {0}" },
                { "Api.ErrorStructuredParseFormat", "Не удалось десериализовать структурированный JSON задания: {0}" },
                { "Api.ErrorStructuredEmpty", "API вернул пустой структурированный результат." },
                { "Api.ErrorEmptyResponse", "API вернул пустой ответ." },
                { "Api.ErrorResponseInvalid", "Не удалось разобрать ответ API." },
                { "Api.ErrorApiReturnedFormat", "API вернул ошибку: {0}" },
                { "Api.ErrorResponsesOutputMissing", "В ответе Responses API отсутствует поле output." },
                { "Api.ErrorRefusalFormat", "Модель отказалась обрабатывать цель: {0}" },
                { "Api.ErrorResponsesIncompleteFormat", "Ответ Responses API не завершён: {0}" },
                { "Api.ErrorResponsesTextMissing", "В ответе Responses API нет пригодного структурированного текста." },
                { "Api.ErrorChatResponseInvalid", "Не удалось разобрать ответ Chat Completions." },
                { "Api.ErrorChatChoicesMissing", "В ответе Chat Completions отсутствует поле choices." },
                { "Api.ErrorChatTextMissing", "В ответе Chat Completions нет пригодного структурированного текста." },
                { "Api.ErrorNoServiceDetails", "Служба не вернула сведения об ошибке." },
                { "Api.ErrorUnknown", "Неизвестная ошибка" },
                { "Api.ConnectionRecoveredFormat", "Подключение восстановлено после попыток: {0}." },
                { "Api.RequestIdSuffixFormat", " (идентификатор запроса: {0})" },
                { "Api.HttpFailureFormat", "Запрос AI API завершился ошибкой HTTP {0}: {1}{2}" },
                { "Api.ErrorTimeoutRetriesExhausted", "Превышено время ожидания 90 секунд, попытки автоматического переподключения исчерпаны." },
                { "Api.ReconnectingFormat", "Временная проблема подключения. Повторная попытка {0}/{1} через {2} мс." },
                { "Api.TransportNoDetails", "Запрос API завершился ошибкой без доступных сведений об исключении." },
                { "Api.ServiceName", "служба API" },
                { "Api.TransportLocalRefusedFormat", "Локальный шлюз API {0} отклонил подключение. Запустите шлюз или маршрут CC Switch и проверьте базовый URL и порт. Исходная ошибка: {1}" },
                { "Api.TransportLocalFormat", "Локальный шлюз API {0} недоступен. Проверьте его состояние, базовый URL и порт. Исходная ошибка: {1}" },
                { "Api.TransportRemoteFormat", "Служба API {0} недоступна. Проверьте сеть, базовый URL, TLS и настройки прокси. Исходная ошибка: {1}" },

                { "Mission.CompilationFailedFormat", "Ошибка локальной компиляции задания: {0}" },
                { "Mission.DescriptionRtl", "Возврат к месту старта после выполнения задания" },
                { "Mission.DescriptionTakeoff", "Проект взлёта самолёта (только локальный план)" },
                { "Mission.DescriptionSpeed", "Установка крейсерской скорости задания" },
                { "Mission.DescriptionSurveyWaypoint", "Точка маршрута съёмочной сетки" },
                { "Mission.DescriptionRelativeLegFormat", "Относительный участок {0}" },

                { "Validation.NoSpec", "GPT не вернул пригодные для разбора параметры задания." },
                { "Validation.NeedsClarification", "Сведения о задании неполны и требуют уточнения." },
                { "Validation.NeedsClarificationFormat", "Требуется уточнение: {0}" },
                { "Validation.SourceSummaryMissing", "Модель не описала понимание исходных материалов; проект нельзя применить." },
                { "Validation.RequirementsMissing", "Модель не перечислила требования задания для подтверждения оператором." },
                { "Validation.HomeInvalid", "Запланированная точка Home в Mission Planner недействительна. Сначала задайте правильную точку Home." },
                { "Validation.MissionTypeInvalid", "Модель вернула неподдерживаемый тип задания." },
                { "Validation.UnsupportedTemplate", "Эту цель нельзя преобразовать в поддерживаемый детерминированный шаблон задания." },
                { "Validation.FieldCruiseAltitude", "Крейсерская высота" },
                { "Validation.FieldCruiseSpeed", "Крейсерская скорость" },
                { "Validation.FieldTakeoffAltitude", "Высота взлёта" },
                { "Validation.CompletionMustRtl", "В качестве завершения задания допускается только RTL." },
                { "Validation.AiNoteFormat", "Примечание GPT: {0}" },
                { "Validation.LocalOnlyWarning", "Проект не загружается автоматически и не может активировать аппарат, выполнить взлёт или изменить режим полёта. Проверьте его и запишите вручную через Mission Planner." },
                { "Validation.NoMissionItems", "Локальный компилятор не создал элементов задания." },
                { "Validation.TooManyItemsFormat", "Количество элементов задания превышает предел {0}." },
                { "Validation.MissionHomeInvalid", "Нельзя проверить дальность задания относительно недействительной точки Home." },
                { "Validation.InvalidCoordinate", "Проект задания содержит недействительные координаты или высоту." },
                { "Validation.WaypointTooFarFormat", "Точка проекта находится за пределом {0:0} м от Home." },
                { "Validation.SegmentDistanceInvalid", "Не удалось вычислить длину участка проекта." },
                { "Validation.NoWaypoints", "Проект задания не содержит допустимых маршрутных точек." },
                { "Validation.RouteTooLongFormat", "Общая длина проекта маршрута превышает {0:0} м." },
                { "Validation.MustEndRtl", "Проект задания должен завершаться командой RETURN_TO_LAUNCH." },
                { "Validation.FieldLaneSpacing", "Шаг линий" },
                { "Validation.FieldGridAngle", "Угол сетки" },
                { "Validation.SurveyPolygonMissing", "Для съёмки необходимо нарисовать в Flight Planner полигон как минимум с тремя вершинами." },
                { "Validation.TooManyVerticesFormat", "Количество вершин полигона превышает предел {0}." },
                { "Validation.PolygonInvalid", "Нарисованный полигон содержит недействительные координаты." },
                { "Validation.PolygonTooFarFormat", "Нарисованная область находится за пределом {0:0} м от Home." },
                { "Validation.NoRelativeLegs", "Относительный маршрут должен содержать хотя бы один участок." },
                { "Validation.TooManyLegsFormat", "Количество относительных участков превышает предел {0}." },
                { "Validation.EmptyLegFormat", "Относительный участок {0} пуст." },
                { "Validation.FieldLegBearingFormat", "Азимут участка {0}" },
                { "Validation.FieldLegDistanceFormat", "Длина участка {0}" },
                { "Validation.FieldLegAltitudeFormat", "Высота участка {0}" },
                { "Validation.RelativeRouteTooLongFormat", "Относительный маршрут модели превышает общий предел {0:0} м." },
                { "Validation.NumberRangeFormat", "Значение «{0}» должно быть от {1:0.###} до {2:0.###}." }
            };
        }
    }
}
