#region netDxf library, Copyright (C) 2009-2016 Daniel Carvajal (haplokuon@gmail.com)

//                        netDxf library
// Copyright (C) 2009-2016 Daniel Carvajal (haplokuon@gmail.com)
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#endregion

using System;

namespace netDxf.Blocks
{
    /// <summary>
    /// Block-type flags (bit-coded values, may be combined).
    /// </summary>
    [Flags]
    public enum BlockTypeFlags
    {
        /// <summary>
        /// Indicates none of the following flags apply.
        /// </summary>
        None = 0,

        /// <summary>
        /// This is an anonymous block generated by hatching, associative dimensioning, other internal operations, or an application.
        /// </summary>
        AnonymousBlock = 1,

        /// <summary>
        /// This block has non-constant attribute definitions
        /// (this bit is not set if the block has any attribute definitions that are constant, or has no attribute definitions at all).
        /// </summary>
        NonConstantAttributeDefinitions = 2,

        /// <summary>
        /// This block is an external reference.
        /// </summary>
        XRef = 4,

        /// <summary>
        /// This block is an external reference overlay.
        /// </summary>
        XRefOverlay = 8,

        /// <summary>
        /// This block is externally dependent.
        /// </summary>
        ExternallyDependent = 16,

        /// <summary>
        /// This is a resolved external reference, or dependent of an external reference (ignored on input).
        /// </summary>
        ResolvedExternalReference = 32,

        /// <summary>
        /// This definition is a referenced external reference (ignored on input).
        /// </summary>
        DefinitionExternalReference = 64
    }
}