/* 
 * Dowding HTTP REST API
 *
 * The Dowding HTTP REST API allows you to add and retrieve contact data from Dowding as well as perform other peripheral functions.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Dowding.Model
{
    /// <summary>
    /// AgentStatusGetDto
    /// </summary>
    [DataContract]
    public partial class AgentStatusGetDto :  IEquatable<AgentStatusGetDto>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentStatusGetDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AgentStatusGetDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentStatusGetDto" /> class.
        /// </summary>
        /// <param name="Health">String representing a built-in test status (i.e. OK, Degraded, Disabled) (required).</param>
        /// <param name="LastCheckin">Number of milliseconds from the unix epoch when last heartbeat from agent received (required).</param>
        public AgentStatusGetDto(string Health = null, decimal? LastCheckin = null)
        {
            // to ensure "Health" is required (not null)
            if (Health == null)
            {
                throw new InvalidDataException("Health is a required property for AgentStatusGetDto and cannot be null");
            }
            else
            {
                this.Health = Health;
            }
            // to ensure "LastCheckin" is required (not null)
            if (LastCheckin == null)
            {
                throw new InvalidDataException("LastCheckin is a required property for AgentStatusGetDto and cannot be null");
            }
            else
            {
                this.LastCheckin = LastCheckin;
            }
        }
        
        /// <summary>
        /// String representing a built-in test status (i.e. OK, Degraded, Disabled)
        /// </summary>
        /// <value>String representing a built-in test status (i.e. OK, Degraded, Disabled)</value>
        [DataMember(Name="health", EmitDefaultValue=false)]
        public string Health { get; set; }
        /// <summary>
        /// Number of milliseconds from the unix epoch when last heartbeat from agent received
        /// </summary>
        /// <value>Number of milliseconds from the unix epoch when last heartbeat from agent received</value>
        [DataMember(Name="last_checkin", EmitDefaultValue=false)]
        public decimal? LastCheckin { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AgentStatusGetDto {\n");
            sb.Append("  Health: ").Append(Health).Append("\n");
            sb.Append("  LastCheckin: ").Append(LastCheckin).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as AgentStatusGetDto);
        }

        /// <summary>
        /// Returns true if AgentStatusGetDto instances are equal
        /// </summary>
        /// <param name="other">Instance of AgentStatusGetDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AgentStatusGetDto other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Health == other.Health ||
                    this.Health != null &&
                    this.Health.Equals(other.Health)
                ) && 
                (
                    this.LastCheckin == other.LastCheckin ||
                    this.LastCheckin != null &&
                    this.LastCheckin.Equals(other.LastCheckin)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Health != null)
                    hash = hash * 59 + this.Health.GetHashCode();
                if (this.LastCheckin != null)
                    hash = hash * 59 + this.LastCheckin.GetHashCode();
                return hash;
            }
        }
    }

}
