/* 
 * Dowding HTTP REST API
 *
 * The Dowding HTTP REST API allows you to add and retrieve contact data from Dowding as well as perform other peripheral functions.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Dowding.Model
{
    /// <summary>
    /// HealthResponse
    /// </summary>
    [DataContract]
    public partial class HealthResponse :  IEquatable<HealthResponse>
    {
        /// <summary>
        /// Will always return true if server responds
        /// </summary>
        /// <value>Will always return true if server responds</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum WebServerEnum
        {
            
            /// <summary>
            /// Enum UP for "UP"
            /// </summary>
            [EnumMember(Value = "UP")]
            UP,
            
            /// <summary>
            /// Enum DOWN for "DOWN"
            /// </summary>
            [EnumMember(Value = "DOWN")]
            DOWN
        }

        /// <summary>
        /// Will always return true if server responds
        /// </summary>
        /// <value>Will always return true if server responds</value>
        [DataMember(Name="webServer", EmitDefaultValue=false)]
        public WebServerEnum? WebServer { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="HealthResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HealthResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HealthResponse" /> class.
        /// </summary>
        /// <param name="WebServer">Will always return true if server responds (required).</param>
        public HealthResponse(WebServerEnum? WebServer = null)
        {
            // to ensure "WebServer" is required (not null)
            if (WebServer == null)
            {
                throw new InvalidDataException("WebServer is a required property for HealthResponse and cannot be null");
            }
            else
            {
                this.WebServer = WebServer;
            }
        }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HealthResponse {\n");
            sb.Append("  WebServer: ").Append(WebServer).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as HealthResponse);
        }

        /// <summary>
        /// Returns true if HealthResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of HealthResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HealthResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.WebServer == other.WebServer ||
                    this.WebServer != null &&
                    this.WebServer.Equals(other.WebServer)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.WebServer != null)
                    hash = hash * 59 + this.WebServer.GetHashCode();
                return hash;
            }
        }
    }

}
