name: OSX Build
on: [push, workflow_dispatch, pull_request]

jobs:
  buildIOS:
    name: Build IOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 10

      - name: Build
        shell: pwsh
        run: |
          msbuild -ver
          dotnet --version
          dotnet --list-sdks
          msbuild -v:m -restore  -p:Configuration=Release "ExtLibs\Xamarin\Xamarin.iOS\Xamarin.iOS.csproj"

      - uses: actions/upload-artifact@v2
        with:
          name: ios
          path: ExtLibs/Xamarin/Xamarin.iOS/bin/iPhoneSimulator/Release/

  buildOSX:
    name: Build OSX
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 10

      - name: Build
        shell: pwsh
        run: |
          msbuild -ver
          dotnet --version
          dotnet --list-sdks
          msbuild -v:m -restore  -p:Configuration=Release "ExtLibs\Xamarin\Xamarin.MacOS\Xamarin.MacOS.csproj"

      - uses: actions/upload-artifact@v2
        with:
          name: osx
          path: |
            ExtLibs/Xamarin/Xamarin.MacOS/bin/Release/*.pkg
            ExtLibs/Xamarin/Xamarin.MacOS/bin/Release/*.app

